// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package iam

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	adminUserThirdPartyFieldNames          = builder.RawFieldNames(&AdminUserThirdParty{})
	adminUserThirdPartyRows                = strings.Join(adminUserThirdPartyFieldNames, ",")
	adminUserThirdPartyRowsExpectAutoSet   = strings.Join(stringx.Remove(adminUserThirdPartyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	adminUserThirdPartyRowsWithPlaceHolder = strings.Join(stringx.Remove(adminUserThirdPartyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAdminUserThirdPartyIdPrefix             = "cache:adminUserThirdParty:id:"
	cacheAdminUserThirdPartyProviderOpenIdPrefix = "cache:adminUserThirdParty:provider:openId:"
)

type (
	adminUserThirdPartyModel interface {
		Insert(ctx context.Context, data *AdminUserThirdParty) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AdminUserThirdParty, error)
		FindOneByProviderOpenId(ctx context.Context, provider string, openId string) (*AdminUserThirdParty, error)
		Update(ctx context.Context, data *AdminUserThirdParty) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAdminUserThirdPartyModel struct {
		sqlc.CachedConn
		table string
	}

	AdminUserThirdParty struct {
		Id        uint64 `db:"id"`         // 主键ID
		UserId    uint64 `db:"user_id"`    // 关联 admin_user.id
		Provider  string `db:"provider"`   // 第三方登录渠道标识，如 feishu
		OpenId    string `db:"open_id"`    // 第三方渠道下的用户唯一标识
		UnionId   string `db:"union_id"`   // 第三方渠道下的开发者主体维度唯一标识
		CreatedAt int64  `db:"created_at"` // 创建时间(秒级时间戳)
		UpdatedAt int64  `db:"updated_at"` // 更新时间(秒级时间戳)
		DeletedAt int64  `db:"deleted_at"` // 删除时间(秒级时间戳,0表示未删除)
	}
)

func newAdminUserThirdPartyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAdminUserThirdPartyModel {
	return &defaultAdminUserThirdPartyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`admin_user_third_party`",
	}
}

func (m *defaultAdminUserThirdPartyModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	adminUserThirdPartyIdKey := fmt.Sprintf("%s%v", cacheAdminUserThirdPartyIdPrefix, id)
	adminUserThirdPartyProviderOpenIdKey := fmt.Sprintf("%s%v:%v", cacheAdminUserThirdPartyProviderOpenIdPrefix, data.Provider, data.OpenId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		// 检查是否有 deleted_at 字段：通过检查结构体字段名列表
		fieldNames := builder.RawFieldNames(&AdminUserThirdParty{})
		fieldNamesStr := strings.Join(fieldNames, ",")
		hasDeletedAt := strings.Contains(fieldNamesStr, "deleted_at")

		var query string
		if hasDeletedAt {
			// 软删除：设置 deleted_at 为当前时间戳
			query = fmt.Sprintf("update %s set deleted_at = UNIX_TIMESTAMP(), updated_at = UNIX_TIMESTAMP() where `id` = ? and deleted_at = 0", m.table)
		} else {
			// 物理删除：直接删除记录
			query = fmt.Sprintf("delete from %s where `id` = ?", m.table)
		}
		return conn.ExecCtx(ctx, query, id)
	}, adminUserThirdPartyIdKey, adminUserThirdPartyProviderOpenIdKey)
	return err
}

func (m *defaultAdminUserThirdPartyModel) FindOne(ctx context.Context, id uint64) (*AdminUserThirdParty, error) {
	// 检查是否有 deleted_at 字段
	hasDeletedAt := strings.Contains(adminUserThirdPartyRows, "deleted_at")
	whereClause := "where `id` = ?"
	if hasDeletedAt {
		whereClause += " and deleted_at = 0"
	}
	adminUserThirdPartyIdKey := fmt.Sprintf("%s%v", cacheAdminUserThirdPartyIdPrefix, id)
	var resp AdminUserThirdParty
	err := m.QueryRowCtx(ctx, &resp, adminUserThirdPartyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s %s limit 1", adminUserThirdPartyRows, m.table, whereClause)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminUserThirdPartyModel) FindOneByProviderOpenId(ctx context.Context, provider string, openId string) (*AdminUserThirdParty, error) {
	// 检查是否有 deleted_at 字段
	hasDeletedAt := strings.Contains(adminUserThirdPartyRows, "deleted_at")
	andClause := ""
	if hasDeletedAt {
		andClause = " and deleted_at = 0"
	}
	adminUserThirdPartyProviderOpenIdKey := fmt.Sprintf("%s%v:%v", cacheAdminUserThirdPartyProviderOpenIdPrefix, provider, openId)
	var resp AdminUserThirdParty
	err := m.QueryRowIndexCtx(ctx, &resp, adminUserThirdPartyProviderOpenIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `provider` = ? and `open_id` = ?%s limit 1", adminUserThirdPartyRows, m.table, andClause)
		if err := conn.QueryRowCtx(ctx, &resp, query, provider, openId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminUserThirdPartyModel) Insert(ctx context.Context, data *AdminUserThirdParty) (sql.Result, error) {
	// 自动设置创建时间和更新时间
	if data.CreatedAt == 0 {
		data.CreatedAt = time.Now().Unix()
	}
	if data.UpdatedAt == 0 {
		data.UpdatedAt = time.Now().Unix()
	}
	// 注意：如果表没有 deleted_at 字段，data.DeletedAt 将不存在，不能访问
	// deleted_at 字段如果存在，它已经在 RowsExpectAutoSet 中，不需要特殊处理
	adminUserThirdPartyIdKey := fmt.Sprintf("%s%v", cacheAdminUserThirdPartyIdPrefix, data.Id)
	adminUserThirdPartyProviderOpenIdKey := fmt.Sprintf("%s%v:%v", cacheAdminUserThirdPartyProviderOpenIdPrefix, data.Provider, data.OpenId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		// 手动构建包含 created_at、updated_at 的插入语句
		// 如果表有 deleted_at 字段，它已经在 RowsExpectAutoSet 中，不需要重复添加
		query := fmt.Sprintf("insert into %s (%s, `created_at`, `updated_at`) values (?, ?, ?, ?, ?, ?, ?)", m.table, adminUserThirdPartyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.Provider, data.OpenId, data.UnionId, data.DeletedAt, data.CreatedAt, data.UpdatedAt)
	}, adminUserThirdPartyIdKey, adminUserThirdPartyProviderOpenIdKey)
	return ret, err
}

func (m *defaultAdminUserThirdPartyModel) Update(ctx context.Context, newData *AdminUserThirdParty) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	adminUserThirdPartyIdKey := fmt.Sprintf("%s%v", cacheAdminUserThirdPartyIdPrefix, data.Id)
	adminUserThirdPartyProviderOpenIdKey := fmt.Sprintf("%s%v:%v", cacheAdminUserThirdPartyProviderOpenIdPrefix, data.Provider, data.OpenId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		// 自动设置更新时间
		newData.UpdatedAt = time.Now().Unix()
		// 检查是否有 deleted_at 字段
		hasDeletedAt := strings.Contains(adminUserThirdPartyRowsWithPlaceHolder, "deleted_at")
		// 手动构建包含 updated_at 的更新语句
		whereClause := "where `id` = ?"
		if hasDeletedAt {
			whereClause += " and deleted_at = 0"
		}
		query := fmt.Sprintf("update %s set %s, `updated_at` = %d %s", m.table, adminUserThirdPartyRowsWithPlaceHolder, newData.UpdatedAt, whereClause)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.Provider, newData.OpenId, newData.UnionId, newData.DeletedAt, newData.Id)
	}, adminUserThirdPartyIdKey, adminUserThirdPartyProviderOpenIdKey)
	return err
}

func (m *defaultAdminUserThirdPartyModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAdminUserThirdPartyIdPrefix, primary)
}

func (m *defaultAdminUserThirdPartyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	// 检查是否有 deleted_at 字段
	hasDeletedAt := strings.Contains(adminUserThirdPartyRows, "deleted_at")
	andClause := ""
	if hasDeletedAt {
		andClause = " and deleted_at = 0"
	}
	query := fmt.Sprintf("select %s from %s where `id` = ?%s limit 1", adminUserThirdPartyRows, m.table, andClause)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAdminUserThirdPartyModel) tableName() string {
	return m.table
}
