version: "3.8"

services:
  web:
    build: .
    ports:
      - "8003:8003"
    depends_on:
      - db
      - redis
    networks:
      - my-network
    volumes:
      - "/etc/data/app:/app/data"
    environment:
      - DB_HOST=db
      - DB_PORT=3309
      - DB_USER=oldbai
      - DB_PASSWORD=123456
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=biz
      - MYSQL_USER=oldbai
      - MYSQL_PASSWORD=123456
    volumes:
      - "/etc/data/mysql:/var/lib/mysql"
    networks:
      - my-network

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
