// 指定proto版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: lbsingle.proto

// 指定默认包名

package client

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	lb "github.com/oldbai555/bgg/service/lb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_Success ErrCode = 0
	// 130000 - 140000
	ErrCode_ErrFileNotFound ErrCode = 130000 // 文件不存在
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:      "Success",
		130000: "ErrFileNotFound",
	}
	ErrCode_value = map[string]int32{
		"Success":         0,
		"ErrFileNotFound": 130000,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_lbsingle_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_lbsingle_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_lbsingle_proto_rawDescGZIP(), []int{0}
}

type GetFileListReq_ListOption int32

const (
	GetFileListReq_ListOptionNil GetFileListReq_ListOption = 0
)

// Enum value maps for GetFileListReq_ListOption.
var (
	GetFileListReq_ListOption_name = map[int32]string{
		0: "ListOptionNil",
	}
	GetFileListReq_ListOption_value = map[string]int32{
		"ListOptionNil": 0,
	}
)

func (x GetFileListReq_ListOption) Enum() *GetFileListReq_ListOption {
	p := new(GetFileListReq_ListOption)
	*p = x
	return p
}

func (x GetFileListReq_ListOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetFileListReq_ListOption) Descriptor() protoreflect.EnumDescriptor {
	return file_lbsingle_proto_enumTypes[1].Descriptor()
}

func (GetFileListReq_ListOption) Type() protoreflect.EnumType {
	return &file_lbsingle_proto_enumTypes[1]
}

func (x GetFileListReq_ListOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetFileListReq_ListOption.Descriptor instead.
func (GetFileListReq_ListOption) EnumDescriptor() ([]byte, []int) {
	return file_lbsingle_proto_rawDescGZIP(), []int{9, 0}
}

type ModelFile struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt uint32 `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt uint32 `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt uint32 `protobuf:"varint,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	CreatorId uint64 `protobuf:"varint,5,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
}

func (x *ModelFile) Reset() {
	*x = ModelFile{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbsingle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelFile) ProtoMessage() {}

func (x *ModelFile) ProtoReflect() protoreflect.Message {
	mi := &file_lbsingle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelFile.ProtoReflect.Descriptor instead.
func (*ModelFile) Descriptor() ([]byte, []int) {
	return file_lbsingle_proto_rawDescGZIP(), []int{0}
}

func (x *ModelFile) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModelFile) GetCreatedAt() uint32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModelFile) GetUpdatedAt() uint32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ModelFile) GetDeletedAt() uint32 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *ModelFile) GetCreatorId() uint64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

type AddFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelFile `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddFileReq) Reset() {
	*x = AddFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbsingle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFileReq) ProtoMessage() {}

func (x *AddFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_lbsingle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFileReq.ProtoReflect.Descriptor instead.
func (*AddFileReq) Descriptor() ([]byte, []int) {
	return file_lbsingle_proto_rawDescGZIP(), []int{1}
}

func (x *AddFileReq) GetData() *ModelFile {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddFileRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelFile `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddFileRsp) Reset() {
	*x = AddFileRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbsingle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFileRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFileRsp) ProtoMessage() {}

func (x *AddFileRsp) ProtoReflect() protoreflect.Message {
	mi := &file_lbsingle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFileRsp.ProtoReflect.Descriptor instead.
func (*AddFileRsp) Descriptor() ([]byte, []int) {
	return file_lbsingle_proto_rawDescGZIP(), []int{2}
}

func (x *AddFileRsp) GetData() *ModelFile {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelFile `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateFileReq) Reset() {
	*x = UpdateFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbsingle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileReq) ProtoMessage() {}

func (x *UpdateFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_lbsingle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileReq.ProtoReflect.Descriptor instead.
func (*UpdateFileReq) Descriptor() ([]byte, []int) {
	return file_lbsingle_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateFileReq) GetData() *ModelFile {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateFileRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateFileRsp) Reset() {
	*x = UpdateFileRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbsingle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateFileRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileRsp) ProtoMessage() {}

func (x *UpdateFileRsp) ProtoReflect() protoreflect.Message {
	mi := &file_lbsingle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileRsp.ProtoReflect.Descriptor instead.
func (*UpdateFileRsp) Descriptor() ([]byte, []int) {
	return file_lbsingle_proto_rawDescGZIP(), []int{4}
}

type DelFileListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @ref_to: GetFileListReq.ListOption
	ListOption *lb.ListOption `protobuf:"bytes,1,opt,name=list_option,json=listOption,proto3" json:"list_option,omitempty"`
}

func (x *DelFileListReq) Reset() {
	*x = DelFileListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbsingle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelFileListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelFileListReq) ProtoMessage() {}

func (x *DelFileListReq) ProtoReflect() protoreflect.Message {
	mi := &file_lbsingle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelFileListReq.ProtoReflect.Descriptor instead.
func (*DelFileListReq) Descriptor() ([]byte, []int) {
	return file_lbsingle_proto_rawDescGZIP(), []int{5}
}

func (x *DelFileListReq) GetListOption() *lb.ListOption {
	if x != nil {
		return x.ListOption
	}
	return nil
}

type DelFileListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelFileListRsp) Reset() {
	*x = DelFileListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbsingle_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelFileListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelFileListRsp) ProtoMessage() {}

func (x *DelFileListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_lbsingle_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelFileListRsp.ProtoReflect.Descriptor instead.
func (*DelFileListRsp) Descriptor() ([]byte, []int) {
	return file_lbsingle_proto_rawDescGZIP(), []int{6}
}

type GetFileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetFileReq) Reset() {
	*x = GetFileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbsingle_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileReq) ProtoMessage() {}

func (x *GetFileReq) ProtoReflect() protoreflect.Message {
	mi := &file_lbsingle_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileReq.ProtoReflect.Descriptor instead.
func (*GetFileReq) Descriptor() ([]byte, []int) {
	return file_lbsingle_proto_rawDescGZIP(), []int{7}
}

func (x *GetFileReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetFileRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelFile `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetFileRsp) Reset() {
	*x = GetFileRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbsingle_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRsp) ProtoMessage() {}

func (x *GetFileRsp) ProtoReflect() protoreflect.Message {
	mi := &file_lbsingle_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRsp.ProtoReflect.Descriptor instead.
func (*GetFileRsp) Descriptor() ([]byte, []int) {
	return file_lbsingle_proto_rawDescGZIP(), []int{8}
}

func (x *GetFileRsp) GetData() *ModelFile {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetFileListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListOption *lb.ListOption `protobuf:"bytes,1,opt,name=list_option,json=listOption,proto3" json:"list_option,omitempty"`
}

func (x *GetFileListReq) Reset() {
	*x = GetFileListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbsingle_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileListReq) ProtoMessage() {}

func (x *GetFileListReq) ProtoReflect() protoreflect.Message {
	mi := &file_lbsingle_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileListReq.ProtoReflect.Descriptor instead.
func (*GetFileListReq) Descriptor() ([]byte, []int) {
	return file_lbsingle_proto_rawDescGZIP(), []int{9}
}

func (x *GetFileListReq) GetListOption() *lb.ListOption {
	if x != nil {
		return x.ListOption
	}
	return nil
}

type GetFileListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paginate *lb.Paginate `protobuf:"bytes,1,opt,name=paginate,proto3" json:"paginate,omitempty"`
	List     []*ModelFile `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetFileListRsp) Reset() {
	*x = GetFileListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbsingle_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFileListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileListRsp) ProtoMessage() {}

func (x *GetFileListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_lbsingle_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileListRsp.ProtoReflect.Descriptor instead.
func (*GetFileListRsp) Descriptor() ([]byte, []int) {
	return file_lbsingle_proto_rawDescGZIP(), []int{10}
}

func (x *GetFileListRsp) GetPaginate() *lb.Paginate {
	if x != nil {
		return x.Paginate
	}
	return nil
}

func (x *GetFileListRsp) GetList() []*ModelFile {
	if x != nil {
		return x.List
	}
	return nil
}

var File_lbsingle_proto protoreflect.FileDescriptor

var file_lbsingle_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6c, 0x62, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6c, 0x62, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x1a, 0x08, 0x6c, 0x62, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x97, 0x01, 0x0a, 0x09, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x3f,
	0x0a, 0x0a, 0x41, 0x64, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x31, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x62, 0x73,
	0x69, 0x6e, 0x67, 0x6c, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x42,
	0x08, 0xfa, 0x42, 0x05, 0x8a, 0x01, 0x02, 0x10, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x35, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x73, 0x70, 0x12, 0x27, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x62,
	0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x46, 0x69, 0x6c, 0x65,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x42, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6c, 0x62, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65,
	0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x8a,
	0x01, 0x02, 0x10, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x0f, 0x0a, 0x0d, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x73, 0x70, 0x22, 0x4b, 0x0a, 0x0e, 0x44,
	0x65, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x39, 0x0a,
	0x0b, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6c, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x8a, 0x01, 0x02, 0x10, 0x01, 0x52, 0x0a, 0x6c, 0x69,
	0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x46,
	0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22, 0x25, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x35, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x73, 0x70, 0x12,
	0x27, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x6c, 0x62, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x46, 0x69,
	0x6c, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6c, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x46,
	0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x39, 0x0a, 0x0b, 0x6c, 0x69,
	0x73, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x6c, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42,
	0x08, 0xfa, 0x42, 0x05, 0x8a, 0x01, 0x02, 0x10, 0x01, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x1f, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x69, 0x6c, 0x10, 0x00, 0x22, 0x63, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x62, 0x2e,
	0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x08, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x6c, 0x62, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x2a, 0x2d, 0x0a, 0x07, 0x45,
	0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x0f, 0x45, 0x72, 0x72, 0x46, 0x69, 0x6c, 0x65, 0x4e, 0x6f,
	0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0xd0, 0xf7, 0x07, 0x32, 0x9a, 0x03, 0x0a, 0x08, 0x6c,
	0x62, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x46, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x14, 0x2e, 0x6c, 0x62, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x2e, 0x41, 0x64,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x6c, 0x62, 0x73, 0x69, 0x6e,
	0x67, 0x6c, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x73, 0x70, 0x22, 0x0f,
	0xa2, 0xe2, 0x09, 0x03, 0x61, 0x64, 0x64, 0xaa, 0xe2, 0x09, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12,
	0x55, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x18,
	0x2e, 0x6c, 0x62, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x46, 0x69, 0x6c,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x6c, 0x62, 0x73, 0x69, 0x6e,
	0x67, 0x6c, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x73, 0x70, 0x22, 0x12, 0xa2, 0xe2, 0x09, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0xaa, 0xe2,
	0x09, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x52, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x46, 0x69, 0x6c, 0x65, 0x12, 0x17, 0x2e, 0x6c, 0x62, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e,
	0x6c, 0x62, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46,
	0x69, 0x6c, 0x65, 0x52, 0x73, 0x70, 0x22, 0x12, 0xa2, 0xe2, 0x09, 0x06, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0xaa, 0xe2, 0x09, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x46, 0x0a, 0x07, 0x47, 0x65,
	0x74, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x14, 0x2e, 0x6c, 0x62, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x6c, 0x62,
	0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x73,
	0x70, 0x22, 0x0f, 0xa2, 0xe2, 0x09, 0x03, 0x67, 0x65, 0x74, 0xaa, 0xe2, 0x09, 0x04, 0x46, 0x69,
	0x6c, 0x65, 0x12, 0x53, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x18, 0x2e, 0x6c, 0x62, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x6c, 0x62,
	0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x73, 0x70, 0x22, 0x10, 0xa2, 0xe2, 0x09, 0x04, 0x6c, 0x69, 0x73, 0x74, 0xaa,
	0xe2, 0x09, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6c, 0x64, 0x62, 0x61, 0x69, 0x35, 0x35, 0x35, 0x2f,
	0x62, 0x67, 0x67, 0x2f, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x73, 0x72, 0x76, 0x2f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lbsingle_proto_rawDescOnce sync.Once
	file_lbsingle_proto_rawDescData = file_lbsingle_proto_rawDesc
)

func file_lbsingle_proto_rawDescGZIP() []byte {
	file_lbsingle_proto_rawDescOnce.Do(func() {
		file_lbsingle_proto_rawDescData = protoimpl.X.CompressGZIP(file_lbsingle_proto_rawDescData)
	})
	return file_lbsingle_proto_rawDescData
}

var file_lbsingle_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_lbsingle_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_lbsingle_proto_goTypes = []interface{}{
	(ErrCode)(0),                   // 0: lbsingle.ErrCode
	(GetFileListReq_ListOption)(0), // 1: lbsingle.GetFileListReq.ListOption
	(*ModelFile)(nil),              // 2: lbsingle.ModelFile
	(*AddFileReq)(nil),             // 3: lbsingle.AddFileReq
	(*AddFileRsp)(nil),             // 4: lbsingle.AddFileRsp
	(*UpdateFileReq)(nil),          // 5: lbsingle.UpdateFileReq
	(*UpdateFileRsp)(nil),          // 6: lbsingle.UpdateFileRsp
	(*DelFileListReq)(nil),         // 7: lbsingle.DelFileListReq
	(*DelFileListRsp)(nil),         // 8: lbsingle.DelFileListRsp
	(*GetFileReq)(nil),             // 9: lbsingle.GetFileReq
	(*GetFileRsp)(nil),             // 10: lbsingle.GetFileRsp
	(*GetFileListReq)(nil),         // 11: lbsingle.GetFileListReq
	(*GetFileListRsp)(nil),         // 12: lbsingle.GetFileListRsp
	(*lb.ListOption)(nil),          // 13: lb.ListOption
	(*lb.Paginate)(nil),            // 14: lb.Paginate
}
var file_lbsingle_proto_depIdxs = []int32{
	2,  // 0: lbsingle.AddFileReq.data:type_name -> lbsingle.ModelFile
	2,  // 1: lbsingle.AddFileRsp.data:type_name -> lbsingle.ModelFile
	2,  // 2: lbsingle.UpdateFileReq.data:type_name -> lbsingle.ModelFile
	13, // 3: lbsingle.DelFileListReq.list_option:type_name -> lb.ListOption
	2,  // 4: lbsingle.GetFileRsp.data:type_name -> lbsingle.ModelFile
	13, // 5: lbsingle.GetFileListReq.list_option:type_name -> lb.ListOption
	14, // 6: lbsingle.GetFileListRsp.paginate:type_name -> lb.Paginate
	2,  // 7: lbsingle.GetFileListRsp.list:type_name -> lbsingle.ModelFile
	3,  // 8: lbsingle.lbsingle.AddFile:input_type -> lbsingle.AddFileReq
	7,  // 9: lbsingle.lbsingle.DelFileList:input_type -> lbsingle.DelFileListReq
	5,  // 10: lbsingle.lbsingle.UpdateFile:input_type -> lbsingle.UpdateFileReq
	9,  // 11: lbsingle.lbsingle.GetFile:input_type -> lbsingle.GetFileReq
	11, // 12: lbsingle.lbsingle.GetFileList:input_type -> lbsingle.GetFileListReq
	4,  // 13: lbsingle.lbsingle.AddFile:output_type -> lbsingle.AddFileRsp
	8,  // 14: lbsingle.lbsingle.DelFileList:output_type -> lbsingle.DelFileListRsp
	6,  // 15: lbsingle.lbsingle.UpdateFile:output_type -> lbsingle.UpdateFileRsp
	10, // 16: lbsingle.lbsingle.GetFile:output_type -> lbsingle.GetFileRsp
	12, // 17: lbsingle.lbsingle.GetFileList:output_type -> lbsingle.GetFileListRsp
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_lbsingle_proto_init() }
func file_lbsingle_proto_init() {
	if File_lbsingle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lbsingle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelFile); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbsingle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbsingle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFileRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbsingle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbsingle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateFileRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbsingle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelFileListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbsingle_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelFileListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbsingle_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbsingle_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbsingle_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbsingle_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFileListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lbsingle_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lbsingle_proto_goTypes,
		DependencyIndexes: file_lbsingle_proto_depIdxs,
		EnumInfos:         file_lbsingle_proto_enumTypes,
		MessageInfos:      file_lbsingle_proto_msgTypes,
	}.Build()
	File_lbsingle_proto = out.File
	file_lbsingle_proto_rawDesc = nil
	file_lbsingle_proto_goTypes = nil
	file_lbsingle_proto_depIdxs = nil
}
