import {
  fitnessLoginConfig,
  fitnessLoginFeishu,
  fitnessMyDay,
  fitnessMyCheckinSave,
  fitnessMyBodyRecordList,
  fitnessMyBodyRecordSave,
  fitnessMyProfile,
  fitnessMyProfileUpdate,
  fitnessMyTemplateSwitch,
  fitnessMySuggestionDecide,
  fitnessTemplateList,
  fitnessTemplateCreate,
  fitnessTemplateUpdate,
  fitnessTemplateDelete,
  fitnessTemplateDays,
  fitnessTemplateDaySave,
  fitnessTemplateDayDelete,
  fitnessTipList,
  fitnessTipCreate,
  fitnessTipUpdate,
  fitnessTipDelete,
  fitnessMemberList,
  fitnessMemberAssign,
  fitnessSwitchList,
  fitnessStatsOverview,
  fitnessCheckinList,
  fitnessMemberDetail,
  fitnessCheckinExport
} from '@/api/generated/admin'

/**
 * 身材管理（fitness 域）API 封装：手机端登录 + my/* 个人数据接口，后台模板/提示/成员/统计接口
 */
export const fitnessApi = {
  loginConfig: fitnessLoginConfig,
  loginFeishu: fitnessLoginFeishu,
  myDay: fitnessMyDay,
  myCheckinSave: fitnessMyCheckinSave,
  myBodyRecordList: fitnessMyBodyRecordList,
  myBodyRecordSave: fitnessMyBodyRecordSave,
  myProfile: fitnessMyProfile,
  myProfileUpdate: fitnessMyProfileUpdate,
  myTemplateSwitch: fitnessMyTemplateSwitch,
  mySuggestionDecide: fitnessMySuggestionDecide,
  templateList: fitnessTemplateList,
  templateCreate: fitnessTemplateCreate,
  templateUpdate: fitnessTemplateUpdate,
  templateDelete: fitnessTemplateDelete,
  templateDays: fitnessTemplateDays,
  templateDaySave: fitnessTemplateDaySave,
  templateDayDelete: fitnessTemplateDayDelete,
  tipList: fitnessTipList,
  tipCreate: fitnessTipCreate,
  tipUpdate: fitnessTipUpdate,
  tipDelete: fitnessTipDelete,
  memberList: fitnessMemberList,
  memberAssign: fitnessMemberAssign,
  switchList: fitnessSwitchList,
  statsOverview: fitnessStatsOverview,
  checkinList: fitnessCheckinList,
  memberDetail: fitnessMemberDetail,
  checkinExport: fitnessCheckinExport
}
