// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lb.proto

package lb // import "github.com/oldbai555/bgg/client/lb"

/*
指定默认包名
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import descriptorpb "google.golang.org/protobuf/types/descriptorpb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrCode int32

const (
	ErrCode_Nil     ErrCode = 0
	ErrCode_Success ErrCode = 200
	// 20000 - 30000
	ErrCode_ErrAnInvalidRequest ErrCode = 20001
	ErrCode_ErrAnInvalidRsp     ErrCode = 20002
)

var ErrCode_name = map[int32]string{
	0:     "Nil",
	200:   "Success",
	20001: "ErrAnInvalidRequest",
	20002: "ErrAnInvalidRsp",
}
var ErrCode_value = map[string]int32{
	"Nil":                 0,
	"Success":             200,
	"ErrAnInvalidRequest": 20001,
	"ErrAnInvalidRsp":     20002,
}

func (x ErrCode) String() string {
	return proto.EnumName(ErrCode_name, int32(x))
}
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_lb_4f2f1e49aba6da40, []int{0}
}

type DefaultOption int32

const (
	DefaultOption_DefaultOptionNil DefaultOption = 0
	// @type: uint32
	DefaultOption_DefaultOptionOrderBy DefaultOption = 101
	// @type: []uint32
	DefaultOption_DefaultOptionCreatedAtRange DefaultOption = 102
)

var DefaultOption_name = map[int32]string{
	0:   "DefaultOptionNil",
	101: "DefaultOptionOrderBy",
	102: "DefaultOptionCreatedAtRange",
}
var DefaultOption_value = map[string]int32{
	"DefaultOptionNil":            0,
	"DefaultOptionOrderBy":        101,
	"DefaultOptionCreatedAtRange": 102,
}

func (x DefaultOption) String() string {
	return proto.EnumName(DefaultOption_name, int32(x))
}
func (DefaultOption) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_lb_4f2f1e49aba6da40, []int{1}
}

type DefaultOrderBy int32

const (
	DefaultOrderBy_DefaultOrderByNil           DefaultOrderBy = 0
	DefaultOrderBy_DefaultOrderByCreatedAtDesc DefaultOrderBy = 101
	DefaultOrderBy_DefaultOrderByCreatedAtAsc  DefaultOrderBy = 102
)

var DefaultOrderBy_name = map[int32]string{
	0:   "DefaultOrderByNil",
	101: "DefaultOrderByCreatedAtDesc",
	102: "DefaultOrderByCreatedAtAsc",
}
var DefaultOrderBy_value = map[string]int32{
	"DefaultOrderByNil":           0,
	"DefaultOrderByCreatedAtDesc": 101,
	"DefaultOrderByCreatedAtAsc":  102,
}

func (x DefaultOrderBy) String() string {
	return proto.EnumName(DefaultOrderBy_name, int32(x))
}
func (DefaultOrderBy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_lb_4f2f1e49aba6da40, []int{2}
}

type Paginate struct {
	Size uint32 `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
	Page uint32 `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`
	// 总行数
	Total                uint64   `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Paginate) Reset()         { *m = Paginate{} }
func (m *Paginate) String() string { return proto.CompactTextString(m) }
func (*Paginate) ProtoMessage()    {}
func (*Paginate) Descriptor() ([]byte, []int) {
	return fileDescriptor_lb_4f2f1e49aba6da40, []int{0}
}
func (m *Paginate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Paginate.Unmarshal(m, b)
}
func (m *Paginate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Paginate.Marshal(b, m, deterministic)
}
func (dst *Paginate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Paginate.Merge(dst, src)
}
func (m *Paginate) XXX_Size() int {
	return xxx_messageInfo_Paginate.Size(m)
}
func (m *Paginate) XXX_DiscardUnknown() {
	xxx_messageInfo_Paginate.DiscardUnknown(m)
}

var xxx_messageInfo_Paginate proto.InternalMessageInfo

func (m *Paginate) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Paginate) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Paginate) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Options struct {
	OptList []*Options_Opt `protobuf:"bytes,1,rep,name=opt_list,json=optList" json:"opt_list,omitempty"`
	Size    uint32         `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Page    uint32         `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
	// 跳过统计总行数
	SkipTotal            bool     `protobuf:"varint,4,opt,name=skip_total,json=skipTotal" json:"skip_total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_lb_4f2f1e49aba6da40, []int{1}
}
func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (dst *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(dst, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetOptList() []*Options_Opt {
	if m != nil {
		return m.OptList
	}
	return nil
}

func (m *Options) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Options) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Options) GetSkipTotal() bool {
	if m != nil {
		return m.SkipTotal
	}
	return false
}

type Options_Opt struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Options_Opt) Reset()         { *m = Options_Opt{} }
func (m *Options_Opt) String() string { return proto.CompactTextString(m) }
func (*Options_Opt) ProtoMessage()    {}
func (*Options_Opt) Descriptor() ([]byte, []int) {
	return fileDescriptor_lb_4f2f1e49aba6da40, []int{1, 0}
}
func (m *Options_Opt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options_Opt.Unmarshal(m, b)
}
func (m *Options_Opt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options_Opt.Marshal(b, m, deterministic)
}
func (dst *Options_Opt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options_Opt.Merge(dst, src)
}
func (m *Options_Opt) XXX_Size() int {
	return xxx_messageInfo_Options_Opt.Size(m)
}
func (m *Options_Opt) XXX_DiscardUnknown() {
	xxx_messageInfo_Options_Opt.DiscardUnknown(m)
}

var xxx_messageInfo_Options_Opt proto.InternalMessageInfo

func (m *Options_Opt) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Options_Opt) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RawReq struct {
	Buf                  []byte   `protobuf:"bytes,1,opt,name=buf,proto3" json:"buf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *RawReq) Reset()         { *m = RawReq{} }
func (m *RawReq) String() string { return proto.CompactTextString(m) }
func (*RawReq) ProtoMessage()    {}
func (*RawReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_lb_4f2f1e49aba6da40, []int{2}
}
func (m *RawReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawReq.Unmarshal(m, b)
}
func (m *RawReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawReq.Marshal(b, m, deterministic)
}
func (dst *RawReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawReq.Merge(dst, src)
}
func (m *RawReq) XXX_Size() int {
	return xxx_messageInfo_RawReq.Size(m)
}
func (m *RawReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RawReq.DiscardUnknown(m)
}

var xxx_messageInfo_RawReq proto.InternalMessageInfo

func (m *RawReq) GetBuf() []byte {
	if m != nil {
		return m.Buf
	}
	return nil
}

type RawRsp struct {
	Buf                  []byte   `protobuf:"bytes,1,opt,name=buf,proto3" json:"buf,omitempty"`
	ContentType          string   `protobuf:"bytes,2,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *RawRsp) Reset()         { *m = RawRsp{} }
func (m *RawRsp) String() string { return proto.CompactTextString(m) }
func (*RawRsp) ProtoMessage()    {}
func (*RawRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_lb_4f2f1e49aba6da40, []int{3}
}
func (m *RawRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawRsp.Unmarshal(m, b)
}
func (m *RawRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawRsp.Marshal(b, m, deterministic)
}
func (dst *RawRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawRsp.Merge(dst, src)
}
func (m *RawRsp) XXX_Size() int {
	return xxx_messageInfo_RawRsp.Size(m)
}
func (m *RawRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RawRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RawRsp proto.InternalMessageInfo

func (m *RawRsp) GetBuf() []byte {
	if m != nil {
		return m.Buf
	}
	return nil
}

func (m *RawRsp) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

var E_ApiMethod = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MethodOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         20001,
	Name:          "lb.ApiMethod",
	Tag:           "bytes,20001,opt,name=ApiMethod",
	Filename:      "lb.proto",
}

var E_AuthType = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.MethodOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         20002,
	Name:          "lb.AuthType",
	Tag:           "bytes,20002,opt,name=AuthType",
	Filename:      "lb.proto",
}

func init() {
	proto.RegisterType((*Paginate)(nil), "lb.Paginate")
	proto.RegisterType((*Options)(nil), "lb.Options")
	proto.RegisterType((*Options_Opt)(nil), "lb.Options.Opt")
	proto.RegisterType((*RawReq)(nil), "lb.RawReq")
	proto.RegisterType((*RawRsp)(nil), "lb.RawRsp")
	proto.RegisterEnum("lb.ErrCode", ErrCode_name, ErrCode_value)
	proto.RegisterEnum("lb.DefaultOption", DefaultOption_name, DefaultOption_value)
	proto.RegisterEnum("lb.DefaultOrderBy", DefaultOrderBy_name, DefaultOrderBy_value)
	proto.RegisterExtension(E_ApiMethod)
	proto.RegisterExtension(E_AuthType)
}

func init() { proto.RegisterFile("lb.proto", fileDescriptor_lb_4f2f1e49aba6da40) }

var fileDescriptor_lb_4f2f1e49aba6da40 = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x6f, 0xd3, 0x4c,
	0x10, 0xc6, 0x5f, 0xc7, 0x69, 0x93, 0x4e, 0xd3, 0xb7, 0x66, 0x49, 0x25, 0x13, 0x44, 0x09, 0x11,
	0x87, 0x28, 0x12, 0xb6, 0x54, 0x94, 0x4b, 0x05, 0x48, 0xe9, 0x1f, 0x09, 0x24, 0x20, 0x68, 0xe9,
	0x89, 0x4b, 0xf0, 0xda, 0x13, 0x67, 0xd5, 0xc5, 0xbb, 0xf5, 0xae, 0x8b, 0xc2, 0x67, 0xc9, 0xa5,
	0xbd, 0xf2, 0x45, 0xf8, 0x58, 0xc8, 0xde, 0x24, 0x34, 0x02, 0xc4, 0x29, 0xb3, 0xbf, 0x67, 0x9e,
	0x79, 0xe2, 0xd1, 0x40, 0x53, 0xb0, 0x40, 0xe5, 0xd2, 0x48, 0x52, 0x13, 0xac, 0xd3, 0x4d, 0xa5,
	0x4c, 0x05, 0x86, 0x15, 0x61, 0xc5, 0x34, 0x4c, 0x50, 0xc7, 0x39, 0x57, 0x46, 0xe6, 0xb6, 0xab,
	0xf7, 0x1a, 0x9a, 0x1f, 0xa2, 0x94, 0x67, 0x91, 0x41, 0x42, 0xa0, 0xae, 0xf9, 0x37, 0xf4, 0x9d,
	0xae, 0xd3, 0xdf, 0xa3, 0x55, 0x5d, 0x32, 0x15, 0xa5, 0xe8, 0xd7, 0x2c, 0x2b, 0x6b, 0xd2, 0x86,
	0x2d, 0x23, 0x4d, 0x24, 0x7c, 0xb7, 0xeb, 0xf4, 0xeb, 0xd4, 0x3e, 0x7a, 0xdf, 0x1d, 0x68, 0x8c,
	0x95, 0xe1, 0x32, 0xd3, 0x64, 0x00, 0x4d, 0xa9, 0xcc, 0x44, 0x70, 0x6d, 0x7c, 0xa7, 0xeb, 0xf6,
	0x77, 0x8f, 0xf6, 0x03, 0xc1, 0x82, 0xa5, 0x5c, 0xfe, 0xd2, 0x86, 0x54, 0xe6, 0x2d, 0xd7, 0x66,
	0x9d, 0x5a, 0xfb, 0x43, 0xaa, 0x7b, 0x27, 0xf5, 0x11, 0x80, 0xbe, 0xe4, 0x6a, 0x62, 0xa3, 0xeb,
	0x5d, 0xa7, 0xdf, 0xa4, 0x3b, 0x25, 0xb9, 0x28, 0x41, 0xe7, 0x19, 0xb8, 0x63, 0x65, 0x88, 0x07,
	0xee, 0x25, 0xce, 0xab, 0x4f, 0xd8, 0xa2, 0x65, 0x59, 0xfe, 0xdb, 0xeb, 0x48, 0x14, 0x36, 0x60,
	0x87, 0xda, 0x47, 0xaf, 0x03, 0xdb, 0x34, 0xfa, 0x4a, 0xf1, 0xaa, 0x74, 0xb0, 0x62, 0x5a, 0x39,
	0x5a, 0xb4, 0x2c, 0x7b, 0x2f, 0xad, 0xa6, 0xd5, 0xef, 0x1a, 0x79, 0x02, 0xad, 0x58, 0x66, 0x06,
	0x33, 0x33, 0x31, 0x73, 0xb5, 0x1a, 0xba, 0xbb, 0x64, 0x17, 0x73, 0x85, 0x03, 0x0a, 0x8d, 0xf3,
	0x3c, 0x3f, 0x95, 0x09, 0x92, 0x06, 0xb8, 0xef, 0xb9, 0xf0, 0xfe, 0x23, 0x2d, 0x68, 0x7c, 0x2c,
	0xe2, 0x18, 0xb5, 0xf6, 0x7e, 0x38, 0xe4, 0x01, 0xdc, 0x3f, 0xcf, 0xf3, 0x51, 0xf6, 0x26, 0xbb,
	0x8e, 0x04, 0x4f, 0x28, 0x5e, 0x15, 0xa8, 0x8d, 0x77, 0xb3, 0x70, 0xc8, 0x01, 0xec, 0x6f, 0x48,
	0x5a, 0x79, 0xb7, 0x0b, 0x67, 0xf0, 0x19, 0xf6, 0xce, 0x70, 0x1a, 0x15, 0xc2, 0xd8, 0x1d, 0x92,
	0x36, 0x78, 0x1b, 0xc0, 0xc6, 0xf8, 0xd0, 0xde, 0xa0, 0xe3, 0x3c, 0xc1, 0xfc, 0x64, 0xee, 0x21,
	0x79, 0x0c, 0x0f, 0x37, 0x94, 0xd3, 0x1c, 0x23, 0x83, 0xc9, 0xc8, 0xd0, 0x28, 0x4b, 0xd1, 0x9b,
	0x0e, 0x66, 0xf0, 0xff, 0xaa, 0xc1, 0x9a, 0xc8, 0x01, 0xdc, 0xdb, 0x24, 0x36, 0xe3, 0xce, 0x24,
	0x8b, 0xd7, 0xa3, 0xce, 0x50, 0xc7, 0x1e, 0x92, 0x43, 0xe8, 0xfc, 0xa5, 0x61, 0xa4, 0x63, 0x6f,
	0x7a, 0x54, 0x87, 0x9a, 0x60, 0xc7, 0xaf, 0x60, 0x67, 0xa4, 0xf8, 0x3b, 0x34, 0x33, 0x99, 0x90,
	0xc3, 0xc0, 0x1e, 0x6a, 0xb0, 0x3a, 0xd4, 0xc0, 0x0a, 0xcb, 0x83, 0xf1, 0x6f, 0x16, 0x4e, 0xb5,
	0xe7, 0x5f, 0x96, 0xe3, 0x17, 0xd0, 0x1c, 0x15, 0x66, 0x56, 0x6e, 0xfc, 0x9f, 0xf6, 0xdb, 0xa5,
	0x7d, 0xed, 0x38, 0x79, 0xfa, 0xa9, 0x97, 0x72, 0x33, 0x2b, 0x58, 0x10, 0xcb, 0x2f, 0xa1, 0x14,
	0x09, 0x8b, 0xf8, 0x70, 0x38, 0x0c, 0x59, 0x9a, 0x86, 0xb1, 0xe0, 0x98, 0x99, 0x50, 0x30, 0xb6,
	0x5d, 0xcd, 0x7b, 0xfe, 0x33, 0x00, 0x00, 0xff, 0xff, 0xd5, 0xb8, 0x73, 0x94, 0x55, 0x03, 0x00,
	0x00,
}
