// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.2
// source: rpc/chat.proto

package chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Chat_ChatList_FullMethodName              = "/chat.Chat/ChatList"
	Chat_ChatMessageList_FullMethodName       = "/chat.Chat/ChatMessageList"
	Chat_ChatMessageSend_FullMethodName       = "/chat.Chat/ChatMessageSend"
	Chat_ChatMessageListAdmin_FullMethodName  = "/chat.Chat/ChatMessageListAdmin"
	Chat_ChatMessageDelete_FullMethodName     = "/chat.Chat/ChatMessageDelete"
	Chat_ChatGroupList_FullMethodName         = "/chat.Chat/ChatGroupList"
	Chat_ChatGroupCreate_FullMethodName       = "/chat.Chat/ChatGroupCreate"
	Chat_ChatGroupUpdate_FullMethodName       = "/chat.Chat/ChatGroupUpdate"
	Chat_ChatGroupDelete_FullMethodName       = "/chat.Chat/ChatGroupDelete"
	Chat_ChatGroupDetail_FullMethodName       = "/chat.Chat/ChatGroupDetail"
	Chat_ChatGroupMemberList_FullMethodName   = "/chat.Chat/ChatGroupMemberList"
	Chat_ChatGroupMemberAdd_FullMethodName    = "/chat.Chat/ChatGroupMemberAdd"
	Chat_ChatGroupMemberRemove_FullMethodName = "/chat.Chat/ChatGroupMemberRemove"
	Chat_PushToUser_FullMethodName            = "/chat.Chat/PushToUser"
	Chat_GetOnlineUserCount_FullMethodName    = "/chat.Chat/GetOnlineUserCount"
	Chat_Stream_FullMethodName                = "/chat.Chat/Stream"
)

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatClient interface {
	ChatList(ctx context.Context, in *ChatListRequest, opts ...grpc.CallOption) (*ChatListResponse, error)
	ChatMessageList(ctx context.Context, in *ChatMessageListRequest, opts ...grpc.CallOption) (*ChatMessageListResponse, error)
	ChatMessageSend(ctx context.Context, in *ChatMessageSendRequest, opts ...grpc.CallOption) (*ChatMessageSendResponse, error)
	ChatMessageListAdmin(ctx context.Context, in *ChatMessageListRequest, opts ...grpc.CallOption) (*ChatMessageListResponse, error)
	ChatMessageDelete(ctx context.Context, in *ChatMessageDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
	ChatGroupList(ctx context.Context, in *ChatGroupListRequest, opts ...grpc.CallOption) (*ChatGroupListResponse, error)
	ChatGroupCreate(ctx context.Context, in *ChatGroupCreateRequest, opts ...grpc.CallOption) (*Empty, error)
	ChatGroupUpdate(ctx context.Context, in *ChatGroupUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
	ChatGroupDelete(ctx context.Context, in *ChatGroupDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
	ChatGroupDetail(ctx context.Context, in *ChatGroupDetailRequest, opts ...grpc.CallOption) (*ChatGroupDetailResponse, error)
	ChatGroupMemberList(ctx context.Context, in *ChatGroupMemberListRequest, opts ...grpc.CallOption) (*ChatGroupMemberListResponse, error)
	ChatGroupMemberAdd(ctx context.Context, in *ChatGroupMemberAddRequest, opts ...grpc.CallOption) (*Empty, error)
	ChatGroupMemberRemove(ctx context.Context, in *ChatGroupMemberRemoveRequest, opts ...grpc.CallOption) (*Empty, error)
	PushToUser(ctx context.Context, in *PushToUserRequest, opts ...grpc.CallOption) (*PushToUserResponse, error)
	GetOnlineUserCount(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetOnlineUserCountResponse, error)
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientFrame, ServerFrame], error)
}

type chatClient struct {
	cc grpc.ClientConnInterface
}

func NewChatClient(cc grpc.ClientConnInterface) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) ChatList(ctx context.Context, in *ChatListRequest, opts ...grpc.CallOption) (*ChatListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatListResponse)
	err := c.cc.Invoke(ctx, Chat_ChatList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) ChatMessageList(ctx context.Context, in *ChatMessageListRequest, opts ...grpc.CallOption) (*ChatMessageListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatMessageListResponse)
	err := c.cc.Invoke(ctx, Chat_ChatMessageList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) ChatMessageSend(ctx context.Context, in *ChatMessageSendRequest, opts ...grpc.CallOption) (*ChatMessageSendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatMessageSendResponse)
	err := c.cc.Invoke(ctx, Chat_ChatMessageSend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) ChatMessageListAdmin(ctx context.Context, in *ChatMessageListRequest, opts ...grpc.CallOption) (*ChatMessageListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatMessageListResponse)
	err := c.cc.Invoke(ctx, Chat_ChatMessageListAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) ChatMessageDelete(ctx context.Context, in *ChatMessageDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Chat_ChatMessageDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) ChatGroupList(ctx context.Context, in *ChatGroupListRequest, opts ...grpc.CallOption) (*ChatGroupListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatGroupListResponse)
	err := c.cc.Invoke(ctx, Chat_ChatGroupList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) ChatGroupCreate(ctx context.Context, in *ChatGroupCreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Chat_ChatGroupCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) ChatGroupUpdate(ctx context.Context, in *ChatGroupUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Chat_ChatGroupUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) ChatGroupDelete(ctx context.Context, in *ChatGroupDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Chat_ChatGroupDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) ChatGroupDetail(ctx context.Context, in *ChatGroupDetailRequest, opts ...grpc.CallOption) (*ChatGroupDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatGroupDetailResponse)
	err := c.cc.Invoke(ctx, Chat_ChatGroupDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) ChatGroupMemberList(ctx context.Context, in *ChatGroupMemberListRequest, opts ...grpc.CallOption) (*ChatGroupMemberListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatGroupMemberListResponse)
	err := c.cc.Invoke(ctx, Chat_ChatGroupMemberList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) ChatGroupMemberAdd(ctx context.Context, in *ChatGroupMemberAddRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Chat_ChatGroupMemberAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) ChatGroupMemberRemove(ctx context.Context, in *ChatGroupMemberRemoveRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Chat_ChatGroupMemberRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) PushToUser(ctx context.Context, in *PushToUserRequest, opts ...grpc.CallOption) (*PushToUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushToUserResponse)
	err := c.cc.Invoke(ctx, Chat_PushToUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) GetOnlineUserCount(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetOnlineUserCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOnlineUserCountResponse)
	err := c.cc.Invoke(ctx, Chat_GetOnlineUserCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientFrame, ServerFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Chat_ServiceDesc.Streams[0], Chat_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientFrame, ServerFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chat_StreamClient = grpc.BidiStreamingClient[ClientFrame, ServerFrame]

// ChatServer is the server API for Chat service.
// All implementations must embed UnimplementedChatServer
// for forward compatibility.
type ChatServer interface {
	ChatList(context.Context, *ChatListRequest) (*ChatListResponse, error)
	ChatMessageList(context.Context, *ChatMessageListRequest) (*ChatMessageListResponse, error)
	ChatMessageSend(context.Context, *ChatMessageSendRequest) (*ChatMessageSendResponse, error)
	ChatMessageListAdmin(context.Context, *ChatMessageListRequest) (*ChatMessageListResponse, error)
	ChatMessageDelete(context.Context, *ChatMessageDeleteRequest) (*Empty, error)
	ChatGroupList(context.Context, *ChatGroupListRequest) (*ChatGroupListResponse, error)
	ChatGroupCreate(context.Context, *ChatGroupCreateRequest) (*Empty, error)
	ChatGroupUpdate(context.Context, *ChatGroupUpdateRequest) (*Empty, error)
	ChatGroupDelete(context.Context, *ChatGroupDeleteRequest) (*Empty, error)
	ChatGroupDetail(context.Context, *ChatGroupDetailRequest) (*ChatGroupDetailResponse, error)
	ChatGroupMemberList(context.Context, *ChatGroupMemberListRequest) (*ChatGroupMemberListResponse, error)
	ChatGroupMemberAdd(context.Context, *ChatGroupMemberAddRequest) (*Empty, error)
	ChatGroupMemberRemove(context.Context, *ChatGroupMemberRemoveRequest) (*Empty, error)
	PushToUser(context.Context, *PushToUserRequest) (*PushToUserResponse, error)
	GetOnlineUserCount(context.Context, *Empty) (*GetOnlineUserCountResponse, error)
	Stream(grpc.BidiStreamingServer[ClientFrame, ServerFrame]) error
	mustEmbedUnimplementedChatServer()
}

// UnimplementedChatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServer struct{}

func (UnimplementedChatServer) ChatList(context.Context, *ChatListRequest) (*ChatListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatList not implemented")
}
func (UnimplementedChatServer) ChatMessageList(context.Context, *ChatMessageListRequest) (*ChatMessageListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatMessageList not implemented")
}
func (UnimplementedChatServer) ChatMessageSend(context.Context, *ChatMessageSendRequest) (*ChatMessageSendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatMessageSend not implemented")
}
func (UnimplementedChatServer) ChatMessageListAdmin(context.Context, *ChatMessageListRequest) (*ChatMessageListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatMessageListAdmin not implemented")
}
func (UnimplementedChatServer) ChatMessageDelete(context.Context, *ChatMessageDeleteRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatMessageDelete not implemented")
}
func (UnimplementedChatServer) ChatGroupList(context.Context, *ChatGroupListRequest) (*ChatGroupListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatGroupList not implemented")
}
func (UnimplementedChatServer) ChatGroupCreate(context.Context, *ChatGroupCreateRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatGroupCreate not implemented")
}
func (UnimplementedChatServer) ChatGroupUpdate(context.Context, *ChatGroupUpdateRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatGroupUpdate not implemented")
}
func (UnimplementedChatServer) ChatGroupDelete(context.Context, *ChatGroupDeleteRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatGroupDelete not implemented")
}
func (UnimplementedChatServer) ChatGroupDetail(context.Context, *ChatGroupDetailRequest) (*ChatGroupDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatGroupDetail not implemented")
}
func (UnimplementedChatServer) ChatGroupMemberList(context.Context, *ChatGroupMemberListRequest) (*ChatGroupMemberListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatGroupMemberList not implemented")
}
func (UnimplementedChatServer) ChatGroupMemberAdd(context.Context, *ChatGroupMemberAddRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatGroupMemberAdd not implemented")
}
func (UnimplementedChatServer) ChatGroupMemberRemove(context.Context, *ChatGroupMemberRemoveRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatGroupMemberRemove not implemented")
}
func (UnimplementedChatServer) PushToUser(context.Context, *PushToUserRequest) (*PushToUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushToUser not implemented")
}
func (UnimplementedChatServer) GetOnlineUserCount(context.Context, *Empty) (*GetOnlineUserCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOnlineUserCount not implemented")
}
func (UnimplementedChatServer) Stream(grpc.BidiStreamingServer[ClientFrame, ServerFrame]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedChatServer) mustEmbedUnimplementedChatServer() {}
func (UnimplementedChatServer) testEmbeddedByValue()              {}

// UnsafeChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServer will
// result in compilation errors.
type UnsafeChatServer interface {
	mustEmbedUnimplementedChatServer()
}

func RegisterChatServer(s grpc.ServiceRegistrar, srv ChatServer) {
	// If the following call panics, it indicates UnimplementedChatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Chat_ServiceDesc, srv)
}

func _Chat_ChatList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).ChatList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_ChatList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).ChatList(ctx, req.(*ChatListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_ChatMessageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).ChatMessageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_ChatMessageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).ChatMessageList(ctx, req.(*ChatMessageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_ChatMessageSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessageSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).ChatMessageSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_ChatMessageSend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).ChatMessageSend(ctx, req.(*ChatMessageSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_ChatMessageListAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).ChatMessageListAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_ChatMessageListAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).ChatMessageListAdmin(ctx, req.(*ChatMessageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_ChatMessageDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatMessageDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).ChatMessageDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_ChatMessageDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).ChatMessageDelete(ctx, req.(*ChatMessageDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_ChatGroupList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatGroupListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).ChatGroupList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_ChatGroupList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).ChatGroupList(ctx, req.(*ChatGroupListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_ChatGroupCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatGroupCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).ChatGroupCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_ChatGroupCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).ChatGroupCreate(ctx, req.(*ChatGroupCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_ChatGroupUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatGroupUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).ChatGroupUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_ChatGroupUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).ChatGroupUpdate(ctx, req.(*ChatGroupUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_ChatGroupDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatGroupDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).ChatGroupDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_ChatGroupDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).ChatGroupDelete(ctx, req.(*ChatGroupDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_ChatGroupDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatGroupDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).ChatGroupDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_ChatGroupDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).ChatGroupDetail(ctx, req.(*ChatGroupDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_ChatGroupMemberList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatGroupMemberListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).ChatGroupMemberList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_ChatGroupMemberList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).ChatGroupMemberList(ctx, req.(*ChatGroupMemberListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_ChatGroupMemberAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatGroupMemberAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).ChatGroupMemberAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_ChatGroupMemberAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).ChatGroupMemberAdd(ctx, req.(*ChatGroupMemberAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_ChatGroupMemberRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatGroupMemberRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).ChatGroupMemberRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_ChatGroupMemberRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).ChatGroupMemberRemove(ctx, req.(*ChatGroupMemberRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_PushToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushToUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).PushToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_PushToUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).PushToUser(ctx, req.(*PushToUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_GetOnlineUserCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServer).GetOnlineUserCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Chat_GetOnlineUserCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServer).GetOnlineUserCount(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chat_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).Stream(&grpc.GenericServerStream[ClientFrame, ServerFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Chat_StreamServer = grpc.BidiStreamingServer[ClientFrame, ServerFrame]

// Chat_ServiceDesc is the grpc.ServiceDesc for Chat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChatList",
			Handler:    _Chat_ChatList_Handler,
		},
		{
			MethodName: "ChatMessageList",
			Handler:    _Chat_ChatMessageList_Handler,
		},
		{
			MethodName: "ChatMessageSend",
			Handler:    _Chat_ChatMessageSend_Handler,
		},
		{
			MethodName: "ChatMessageListAdmin",
			Handler:    _Chat_ChatMessageListAdmin_Handler,
		},
		{
			MethodName: "ChatMessageDelete",
			Handler:    _Chat_ChatMessageDelete_Handler,
		},
		{
			MethodName: "ChatGroupList",
			Handler:    _Chat_ChatGroupList_Handler,
		},
		{
			MethodName: "ChatGroupCreate",
			Handler:    _Chat_ChatGroupCreate_Handler,
		},
		{
			MethodName: "ChatGroupUpdate",
			Handler:    _Chat_ChatGroupUpdate_Handler,
		},
		{
			MethodName: "ChatGroupDelete",
			Handler:    _Chat_ChatGroupDelete_Handler,
		},
		{
			MethodName: "ChatGroupDetail",
			Handler:    _Chat_ChatGroupDetail_Handler,
		},
		{
			MethodName: "ChatGroupMemberList",
			Handler:    _Chat_ChatGroupMemberList_Handler,
		},
		{
			MethodName: "ChatGroupMemberAdd",
			Handler:    _Chat_ChatGroupMemberAdd_Handler,
		},
		{
			MethodName: "ChatGroupMemberRemove",
			Handler:    _Chat_ChatGroupMemberRemove_Handler,
		},
		{
			MethodName: "PushToUser",
			Handler:    _Chat_PushToUser_Handler,
		},
		{
			MethodName: "GetOnlineUserCount",
			Handler:    _Chat_GetOnlineUserCount_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Chat_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rpc/chat.proto",
}
