// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sdk

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sdkKeyFieldNames          = builder.RawFieldNames(&SdkKey{})
	sdkKeyRows                = strings.Join(sdkKeyFieldNames, ",")
	sdkKeyRowsExpectAutoSet   = strings.Join(stringx.Remove(sdkKeyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sdkKeyRowsWithPlaceHolder = strings.Join(stringx.Remove(sdkKeyFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheSdkKeyIdPrefix        = "cache:sdkKey:id:"
	cacheSdkKeyApiKeyPrefix    = "cache:sdkKey:apiKey:"
	cacheSdkKeyApiSecretPrefix = "cache:sdkKey:apiSecret:"
)

type (
	sdkKeyModel interface {
		Insert(ctx context.Context, data *SdkKey) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*SdkKey, error)
		FindOneByApiKey(ctx context.Context, apiKey string) (*SdkKey, error)
		FindOneByApiSecret(ctx context.Context, apiSecret string) (*SdkKey, error)
		Update(ctx context.Context, data *SdkKey) error
		Delete(ctx context.Context, id uint64) error
		FindPage(ctx context.Context, page, pageSize int64) ([]SdkKey, int64, error)
		FindChunk(ctx context.Context, limit int64, lastId uint64) ([]SdkKey, uint64, error)
	}

	defaultSdkKeyModel struct {
		sqlc.CachedConn
		table string
	}

	SdkKey struct {
		Id          uint64 `db:"id"`           // 主键 ID
		Name        string `db:"name"`         // 名称
		ApiKey      string `db:"api_key"`      // 对外 API Key（唯一）
		ApiSecret   string `db:"api_secret"`   // 对外 API Secret（唯一）
		Status      int64  `db:"status"`       // 状态：1启用 0禁用
		ExpireAt    int64  `db:"expire_at"`    // 过期时间(秒级时间戳)，0 表示长期有效
		IpWhitelist string `db:"ip_whitelist"` // IP 白名单，逗号或换行分隔，空表示不限制
		Remark      string `db:"remark"`       // 备注
		CreatedAt   int64  `db:"created_at"`   // 创建时间(秒级时间戳)
		UpdatedAt   int64  `db:"updated_at"`   // 更新时间(秒级时间戳)
		DeletedAt   int64  `db:"deleted_at"`   // 删除时间(秒级时间戳,0表示未删除)
	}
)

func newSdkKeyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultSdkKeyModel {
	return &defaultSdkKeyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`sdk_key`",
	}
}

func (m *defaultSdkKeyModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	sdkKeyApiKeyKey := fmt.Sprintf("%s%v", cacheSdkKeyApiKeyPrefix, data.ApiKey)
	sdkKeyApiSecretKey := fmt.Sprintf("%s%v", cacheSdkKeyApiSecretPrefix, data.ApiSecret)
	sdkKeyIdKey := fmt.Sprintf("%s%v", cacheSdkKeyIdPrefix, id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		// 检查是否有 deleted_at 字段：通过检查结构体字段名列表
		fieldNames := builder.RawFieldNames(&SdkKey{})
		fieldNamesStr := strings.Join(fieldNames, ",")
		hasDeletedAt := strings.Contains(fieldNamesStr, "deleted_at")

		var query string
		if hasDeletedAt {
			// 软删除：设置 deleted_at 为当前时间戳
			query = fmt.Sprintf("update %s set deleted_at = UNIX_TIMESTAMP(), updated_at = UNIX_TIMESTAMP() where `id` = ? and deleted_at = 0", m.table)
		} else {
			// 物理删除：直接删除记录
			query = fmt.Sprintf("delete from %s where `id` = ?", m.table)
		}
		return conn.ExecCtx(ctx, query, id)
	}, sdkKeyApiKeyKey, sdkKeyApiSecretKey, sdkKeyIdKey)
	return err
}

func (m *defaultSdkKeyModel) FindOne(ctx context.Context, id uint64) (*SdkKey, error) {
	// 检查是否有 deleted_at 字段
	hasDeletedAt := strings.Contains(sdkKeyRows, "deleted_at")
	whereClause := "where `id` = ?"
	if hasDeletedAt {
		whereClause += " and deleted_at = 0"
	}
	sdkKeyIdKey := fmt.Sprintf("%s%v", cacheSdkKeyIdPrefix, id)
	var resp SdkKey
	err := m.QueryRowCtx(ctx, &resp, sdkKeyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s %s limit 1", sdkKeyRows, m.table, whereClause)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSdkKeyModel) FindOneByApiKey(ctx context.Context, apiKey string) (*SdkKey, error) {
	// 检查是否有 deleted_at 字段
	hasDeletedAt := strings.Contains(sdkKeyRows, "deleted_at")
	andClause := ""
	if hasDeletedAt {
		andClause = " and deleted_at = 0"
	}
	sdkKeyApiKeyKey := fmt.Sprintf("%s%v", cacheSdkKeyApiKeyPrefix, apiKey)
	var resp SdkKey
	err := m.QueryRowIndexCtx(ctx, &resp, sdkKeyApiKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `api_key` = ?%s limit 1", sdkKeyRows, m.table, andClause)
		if err := conn.QueryRowCtx(ctx, &resp, query, apiKey); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSdkKeyModel) FindOneByApiSecret(ctx context.Context, apiSecret string) (*SdkKey, error) {
	// 检查是否有 deleted_at 字段
	hasDeletedAt := strings.Contains(sdkKeyRows, "deleted_at")
	andClause := ""
	if hasDeletedAt {
		andClause = " and deleted_at = 0"
	}
	sdkKeyApiSecretKey := fmt.Sprintf("%s%v", cacheSdkKeyApiSecretPrefix, apiSecret)
	var resp SdkKey
	err := m.QueryRowIndexCtx(ctx, &resp, sdkKeyApiSecretKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `api_secret` = ?%s limit 1", sdkKeyRows, m.table, andClause)
		if err := conn.QueryRowCtx(ctx, &resp, query, apiSecret); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSdkKeyModel) Insert(ctx context.Context, data *SdkKey) (sql.Result, error) {
	// 自动设置创建时间和更新时间
	if data.CreatedAt == 0 {
		data.CreatedAt = time.Now().Unix()
	}
	if data.UpdatedAt == 0 {
		data.UpdatedAt = time.Now().Unix()
	}
	// 注意：如果表没有 deleted_at 字段，data.DeletedAt 将不存在，不能访问
	// deleted_at 字段如果存在，它已经在 RowsExpectAutoSet 中，不需要特殊处理
	sdkKeyApiKeyKey := fmt.Sprintf("%s%v", cacheSdkKeyApiKeyPrefix, data.ApiKey)
	sdkKeyApiSecretKey := fmt.Sprintf("%s%v", cacheSdkKeyApiSecretPrefix, data.ApiSecret)
	sdkKeyIdKey := fmt.Sprintf("%s%v", cacheSdkKeyIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		// 手动构建包含 created_at、updated_at 的插入语句
		// 如果表有 deleted_at 字段，它已经在 RowsExpectAutoSet 中，不需要重复添加
		query := fmt.Sprintf("insert into %s (%s, `created_at`, `updated_at`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sdkKeyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.ApiKey, data.ApiSecret, data.Status, data.ExpireAt, data.IpWhitelist, data.Remark, data.DeletedAt, data.CreatedAt, data.UpdatedAt)
	}, sdkKeyApiKeyKey, sdkKeyApiSecretKey, sdkKeyIdKey)
	return ret, err
}

func (m *defaultSdkKeyModel) Update(ctx context.Context, newData *SdkKey) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	sdkKeyApiKeyKey := fmt.Sprintf("%s%v", cacheSdkKeyApiKeyPrefix, data.ApiKey)
	sdkKeyApiSecretKey := fmt.Sprintf("%s%v", cacheSdkKeyApiSecretPrefix, data.ApiSecret)
	sdkKeyIdKey := fmt.Sprintf("%s%v", cacheSdkKeyIdPrefix, data.Id)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		// 自动设置更新时间
		newData.UpdatedAt = time.Now().Unix()
		// 检查是否有 deleted_at 字段
		hasDeletedAt := strings.Contains(sdkKeyRowsWithPlaceHolder, "deleted_at")
		// 手动构建包含 updated_at 的更新语句
		whereClause := "where `id` = ?"
		if hasDeletedAt {
			whereClause += " and deleted_at = 0"
		}
		query := fmt.Sprintf("update %s set %s, `updated_at` = %d %s", m.table, sdkKeyRowsWithPlaceHolder, newData.UpdatedAt, whereClause)
		return conn.ExecCtx(ctx, query, newData.Name, newData.ApiKey, newData.ApiSecret, newData.Status, newData.ExpireAt, newData.IpWhitelist, newData.Remark, newData.DeletedAt, newData.Id)
	}, sdkKeyApiKeyKey, sdkKeyApiSecretKey, sdkKeyIdKey)
	return err
}

func (m *defaultSdkKeyModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheSdkKeyIdPrefix, primary)
}

func (m *defaultSdkKeyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	// 检查是否有 deleted_at 字段
	hasDeletedAt := strings.Contains(sdkKeyRows, "deleted_at")
	andClause := ""
	if hasDeletedAt {
		andClause = " and deleted_at = 0"
	}
	query := fmt.Sprintf("select %s from %s where `id` = ?%s limit 1", sdkKeyRows, m.table, andClause)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultSdkKeyModel) tableName() string {
	return m.table
}

// 分页查询：根据页码和每页数量查询数据
func (m *defaultSdkKeyModel) FindPage(ctx context.Context, page, pageSize int64) ([]SdkKey, int64, error) {
	if page <= 0 {
		page = 1
	}
	if pageSize <= 0 {
		pageSize = 20
	}
	if pageSize > 100 {
		pageSize = 100
	}

	offset := (page - 1) * pageSize

	// 检查是否有 deleted_at 字段
	hasDeletedAt := strings.Contains(sdkKeyRows, "deleted_at")
	whereClause := ""
	if hasDeletedAt {
		whereClause = "where deleted_at = 0"
	}

	// 查询总数
	var total int64
	countQuery := fmt.Sprintf("select count(*) from %s %s", m.table, whereClause)
	err := m.QueryRowNoCacheCtx(ctx, &total, countQuery)
	if err != nil {
		return nil, 0, err
	}

	// 查询分页数据
	var list []SdkKey
	query := fmt.Sprintf("select %s from %s %s order by id desc limit %d offset %d", sdkKeyRows, m.table, whereClause, pageSize, offset)
	err = m.QueryRowsNoCacheCtx(ctx, &list, query)
	if err != nil {
		return nil, 0, err
	}

	return list, total, nil
}

// 分片查询：基于lastId的分片查询，一次查询limit条，返回数据和下次查询的lastId
// lastId=0表示第一次查询，返回的lastId用于下次查询，当返回的lastId=0或数据为空时表示无更多数据
func (m *defaultSdkKeyModel) FindChunk(ctx context.Context, limit int64, lastId uint64) ([]SdkKey, uint64, error) {
	if limit <= 0 {
		limit = 20
	}
	if limit > 100 {
		limit = 100
	}

	var list []SdkKey
	var err error

	// 检查是否有 deleted_at 字段
	hasDeletedAt := strings.Contains(sdkKeyRows, "deleted_at")
	whereClause := ""
	if hasDeletedAt {
		whereClause = "where deleted_at = 0"
	}

	if lastId == 0 {
		// 第一次查询
		query := fmt.Sprintf("select %s from %s %s order by id asc limit %d", sdkKeyRows, m.table, whereClause, limit)
		err = m.QueryRowsNoCacheCtx(ctx, &list, query)
	} else {
		// 基于lastId的分片查询
		andClause := ""
		if hasDeletedAt {
			andClause = "where deleted_at = 0 and id > ?"
		} else {
			andClause = "where id > ?"
		}
		query := fmt.Sprintf("select %s from %s %s order by id asc limit %d", sdkKeyRows, m.table, andClause, limit)
		err = m.QueryRowsNoCacheCtx(ctx, &list, query, lastId)
	}

	if err != nil {
		return nil, 0, err
	}

	// 返回最后一条记录的ID，用于下次查询；如果数据为空，返回0表示无更多数据
	nextLastId := uint64(0)
	if len(list) > 0 {
		nextLastId = list[len(list)-1].Id
	}

	return list, nextLastId, nil
}
