// 指定proto版本

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: lbblog.proto

// 指定默认包名

package lbblog

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	lb "github.com/oldbai555/bgg/service/lb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrCode int32

const (
	ErrCode_Nil ErrCode = 0
	// 40000 - 50000
	ErrCode_ErrArticleNotFound  ErrCode = 40000
	ErrCode_ErrCategoryNotFound ErrCode = 40001
	ErrCode_ErrCommentNotFound  ErrCode = 40002
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:     "Nil",
		40000: "ErrArticleNotFound",
		40001: "ErrCategoryNotFound",
		40002: "ErrCommentNotFound",
	}
	ErrCode_value = map[string]int32{
		"Nil":                 0,
		"ErrArticleNotFound":  40000,
		"ErrCategoryNotFound": 40001,
		"ErrCommentNotFound":  40002,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_lbblog_proto_enumTypes[0].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_lbblog_proto_enumTypes[0]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{0}
}

type ModelComment_Status int32

const (
	ModelComment_StatusNil      ModelComment_Status = 0
	ModelComment_StatusNormal   ModelComment_Status = 1 // 正常
	ModelComment_StatusReview   ModelComment_Status = 2 // 审核中
	ModelComment_StatusTakeDown ModelComment_Status = 3 // 撤下
)

// Enum value maps for ModelComment_Status.
var (
	ModelComment_Status_name = map[int32]string{
		0: "StatusNil",
		1: "StatusNormal",
		2: "StatusReview",
		3: "StatusTakeDown",
	}
	ModelComment_Status_value = map[string]int32{
		"StatusNil":      0,
		"StatusNormal":   1,
		"StatusReview":   2,
		"StatusTakeDown": 3,
	}
)

func (x ModelComment_Status) Enum() *ModelComment_Status {
	p := new(ModelComment_Status)
	*p = x
	return p
}

func (x ModelComment_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModelComment_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_lbblog_proto_enumTypes[1].Descriptor()
}

func (ModelComment_Status) Type() protoreflect.EnumType {
	return &file_lbblog_proto_enumTypes[1]
}

func (x ModelComment_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModelComment_Status.Descriptor instead.
func (ModelComment_Status) EnumDescriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{2, 0}
}

type GetArticleListReq_ListOption int32

const (
	GetArticleListReq_ListOptionNil    GetArticleListReq_ListOption = 0
	GetArticleListReq_OptionCategoryId GetArticleListReq_ListOption = 1
	GetArticleListReq_OptionLikeTitle  GetArticleListReq_ListOption = 2
)

// Enum value maps for GetArticleListReq_ListOption.
var (
	GetArticleListReq_ListOption_name = map[int32]string{
		0: "ListOptionNil",
		1: "OptionCategoryId",
		2: "OptionLikeTitle",
	}
	GetArticleListReq_ListOption_value = map[string]int32{
		"ListOptionNil":    0,
		"OptionCategoryId": 1,
		"OptionLikeTitle":  2,
	}
)

func (x GetArticleListReq_ListOption) Enum() *GetArticleListReq_ListOption {
	p := new(GetArticleListReq_ListOption)
	*p = x
	return p
}

func (x GetArticleListReq_ListOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetArticleListReq_ListOption) Descriptor() protoreflect.EnumDescriptor {
	return file_lbblog_proto_enumTypes[2].Descriptor()
}

func (GetArticleListReq_ListOption) Type() protoreflect.EnumType {
	return &file_lbblog_proto_enumTypes[2]
}

func (x GetArticleListReq_ListOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetArticleListReq_ListOption.Descriptor instead.
func (GetArticleListReq_ListOption) EnumDescriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{11, 0}
}

type GetCategoryListReq_ListOption int32

const (
	GetCategoryListReq_ListOptionNil  GetCategoryListReq_ListOption = 0
	GetCategoryListReq_OptionLikeName GetCategoryListReq_ListOption = 1
)

// Enum value maps for GetCategoryListReq_ListOption.
var (
	GetCategoryListReq_ListOption_name = map[int32]string{
		0: "ListOptionNil",
		1: "OptionLikeName",
	}
	GetCategoryListReq_ListOption_value = map[string]int32{
		"ListOptionNil":  0,
		"OptionLikeName": 1,
	}
)

func (x GetCategoryListReq_ListOption) Enum() *GetCategoryListReq_ListOption {
	p := new(GetCategoryListReq_ListOption)
	*p = x
	return p
}

func (x GetCategoryListReq_ListOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetCategoryListReq_ListOption) Descriptor() protoreflect.EnumDescriptor {
	return file_lbblog_proto_enumTypes[3].Descriptor()
}

func (GetCategoryListReq_ListOption) Type() protoreflect.EnumType {
	return &file_lbblog_proto_enumTypes[3]
}

func (x GetCategoryListReq_ListOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetCategoryListReq_ListOption.Descriptor instead.
func (GetCategoryListReq_ListOption) EnumDescriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{21, 0}
}

type GetCommentListReq_ListOption int32

const (
	GetCommentListReq_ListOptionNil       GetCommentListReq_ListOption = 0
	GetCommentListReq_OptionArticleId     GetCommentListReq_ListOption = 1
	GetCommentListReq_OptionLikeContent   GetCommentListReq_ListOption = 2
	GetCommentListReq_OptionStatus        GetCommentListReq_ListOption = 3
	GetCommentListReq_OptionLikeUserEmail GetCommentListReq_ListOption = 4
	GetCommentListReq_OptionArticleIdList GetCommentListReq_ListOption = 5
)

// Enum value maps for GetCommentListReq_ListOption.
var (
	GetCommentListReq_ListOption_name = map[int32]string{
		0: "ListOptionNil",
		1: "OptionArticleId",
		2: "OptionLikeContent",
		3: "OptionStatus",
		4: "OptionLikeUserEmail",
		5: "OptionArticleIdList",
	}
	GetCommentListReq_ListOption_value = map[string]int32{
		"ListOptionNil":       0,
		"OptionArticleId":     1,
		"OptionLikeContent":   2,
		"OptionStatus":        3,
		"OptionLikeUserEmail": 4,
		"OptionArticleIdList": 5,
	}
)

func (x GetCommentListReq_ListOption) Enum() *GetCommentListReq_ListOption {
	p := new(GetCommentListReq_ListOption)
	*p = x
	return p
}

func (x GetCommentListReq_ListOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetCommentListReq_ListOption) Descriptor() protoreflect.EnumDescriptor {
	return file_lbblog_proto_enumTypes[4].Descriptor()
}

func (GetCommentListReq_ListOption) Type() protoreflect.EnumType {
	return &file_lbblog_proto_enumTypes[4]
}

func (x GetCommentListReq_ListOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetCommentListReq_ListOption.Descriptor instead.
func (GetCommentListReq_ListOption) EnumDescriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{31, 0}
}

type ModelArticle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt int32  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt int32  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt int32  `protobuf:"varint,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	// @desc:文章标题
	Title string `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	// @desc:文章描述
	Desc string `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	// @desc:文章分类
	CategoryId uint64 `protobuf:"varint,7,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	// @desc:文章缩略图
	Img string `protobuf:"bytes,8,opt,name=img,proto3" json:"img,omitempty"`
	// @desc:文章内容
	Content string `protobuf:"bytes,9,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ModelArticle) Reset() {
	*x = ModelArticle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelArticle) ProtoMessage() {}

func (x *ModelArticle) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelArticle.ProtoReflect.Descriptor instead.
func (*ModelArticle) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{0}
}

func (x *ModelArticle) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModelArticle) GetCreatedAt() int32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModelArticle) GetUpdatedAt() int32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ModelArticle) GetDeletedAt() int32 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *ModelArticle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ModelArticle) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ModelArticle) GetCategoryId() uint64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ModelArticle) GetImg() string {
	if x != nil {
		return x.Img
	}
	return ""
}

func (x *ModelArticle) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ModelCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt int32  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt int32  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt int32  `protobuf:"varint,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Name      string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ModelCategory) Reset() {
	*x = ModelCategory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelCategory) ProtoMessage() {}

func (x *ModelCategory) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelCategory.ProtoReflect.Descriptor instead.
func (*ModelCategory) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{1}
}

func (x *ModelCategory) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModelCategory) GetCreatedAt() int32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModelCategory) GetUpdatedAt() int32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ModelCategory) GetDeletedAt() int32 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *ModelCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ModelComment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt int32  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt int32  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt int32  `protobuf:"varint,4,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	// @desc: 文章
	ArticleId uint64 `protobuf:"varint,5,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// @desc: 评论用户 系统用户
	UserId uint64 `protobuf:"varint,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// @desc: 评论用户留下的邮箱 非系统用户
	UserEmail string `protobuf:"bytes,7,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	// @desc: 评论内容
	Content string `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	// @desc: 评论状态
	// @ref_to: Comment.Status
	Status uint64 `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *ModelComment) Reset() {
	*x = ModelComment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModelComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelComment) ProtoMessage() {}

func (x *ModelComment) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelComment.ProtoReflect.Descriptor instead.
func (*ModelComment) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{2}
}

func (x *ModelComment) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ModelComment) GetCreatedAt() int32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ModelComment) GetUpdatedAt() int32 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ModelComment) GetDeletedAt() int32 {
	if x != nil {
		return x.DeletedAt
	}
	return 0
}

func (x *ModelComment) GetArticleId() uint64 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *ModelComment) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ModelComment) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *ModelComment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ModelComment) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AddArticleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelArticle `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddArticleReq) Reset() {
	*x = AddArticleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArticleReq) ProtoMessage() {}

func (x *AddArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArticleReq.ProtoReflect.Descriptor instead.
func (*AddArticleReq) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{3}
}

func (x *AddArticleReq) GetData() *ModelArticle {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddArticleRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelArticle `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddArticleRsp) Reset() {
	*x = AddArticleRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddArticleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddArticleRsp) ProtoMessage() {}

func (x *AddArticleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddArticleRsp.ProtoReflect.Descriptor instead.
func (*AddArticleRsp) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{4}
}

func (x *AddArticleRsp) GetData() *ModelArticle {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateArticleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelArticle `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateArticleReq) Reset() {
	*x = UpdateArticleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleReq) ProtoMessage() {}

func (x *UpdateArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleReq.ProtoReflect.Descriptor instead.
func (*UpdateArticleReq) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateArticleReq) GetData() *ModelArticle {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateArticleRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateArticleRsp) Reset() {
	*x = UpdateArticleRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateArticleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRsp) ProtoMessage() {}

func (x *UpdateArticleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRsp.ProtoReflect.Descriptor instead.
func (*UpdateArticleRsp) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{6}
}

type DelArticleListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @ref_to: GetArticleListReq.ListOption
	ListOption *lb.ListOption `protobuf:"bytes,1,opt,name=list_option,json=listOption,proto3" json:"list_option,omitempty"`
}

func (x *DelArticleListReq) Reset() {
	*x = DelArticleListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelArticleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelArticleListReq) ProtoMessage() {}

func (x *DelArticleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelArticleListReq.ProtoReflect.Descriptor instead.
func (*DelArticleListReq) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{7}
}

func (x *DelArticleListReq) GetListOption() *lb.ListOption {
	if x != nil {
		return x.ListOption
	}
	return nil
}

type DelArticleListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelArticleListRsp) Reset() {
	*x = DelArticleListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelArticleListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelArticleListRsp) ProtoMessage() {}

func (x *DelArticleListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelArticleListRsp.ProtoReflect.Descriptor instead.
func (*DelArticleListRsp) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{8}
}

type GetArticleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetArticleReq) Reset() {
	*x = GetArticleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArticleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleReq) ProtoMessage() {}

func (x *GetArticleReq) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleReq.ProtoReflect.Descriptor instead.
func (*GetArticleReq) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{9}
}

func (x *GetArticleReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetArticleRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelArticle `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetArticleRsp) Reset() {
	*x = GetArticleRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArticleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRsp) ProtoMessage() {}

func (x *GetArticleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRsp.ProtoReflect.Descriptor instead.
func (*GetArticleRsp) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{10}
}

func (x *GetArticleRsp) GetData() *ModelArticle {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetArticleListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListOption *lb.ListOption `protobuf:"bytes,1,opt,name=list_option,json=listOption,proto3" json:"list_option,omitempty"`
}

func (x *GetArticleListReq) Reset() {
	*x = GetArticleListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArticleListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleListReq) ProtoMessage() {}

func (x *GetArticleListReq) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleListReq.ProtoReflect.Descriptor instead.
func (*GetArticleListReq) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{11}
}

func (x *GetArticleListReq) GetListOption() *lb.ListOption {
	if x != nil {
		return x.ListOption
	}
	return nil
}

type GetArticleListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paginate *lb.Paginate    `protobuf:"bytes,1,opt,name=paginate,proto3" json:"paginate,omitempty"`
	List     []*ModelArticle `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetArticleListRsp) Reset() {
	*x = GetArticleListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArticleListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleListRsp) ProtoMessage() {}

func (x *GetArticleListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleListRsp.ProtoReflect.Descriptor instead.
func (*GetArticleListRsp) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{12}
}

func (x *GetArticleListRsp) GetPaginate() *lb.Paginate {
	if x != nil {
		return x.Paginate
	}
	return nil
}

func (x *GetArticleListRsp) GetList() []*ModelArticle {
	if x != nil {
		return x.List
	}
	return nil
}

type AddCategoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelCategory `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddCategoryReq) Reset() {
	*x = AddCategoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCategoryReq) ProtoMessage() {}

func (x *AddCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCategoryReq.ProtoReflect.Descriptor instead.
func (*AddCategoryReq) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{13}
}

func (x *AddCategoryReq) GetData() *ModelCategory {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddCategoryRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelCategory `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddCategoryRsp) Reset() {
	*x = AddCategoryRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCategoryRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCategoryRsp) ProtoMessage() {}

func (x *AddCategoryRsp) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCategoryRsp.ProtoReflect.Descriptor instead.
func (*AddCategoryRsp) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{14}
}

func (x *AddCategoryRsp) GetData() *ModelCategory {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateCategoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelCategory `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateCategoryReq) Reset() {
	*x = UpdateCategoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryReq) ProtoMessage() {}

func (x *UpdateCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryReq.ProtoReflect.Descriptor instead.
func (*UpdateCategoryReq) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateCategoryReq) GetData() *ModelCategory {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateCategoryRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateCategoryRsp) Reset() {
	*x = UpdateCategoryRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCategoryRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRsp) ProtoMessage() {}

func (x *UpdateCategoryRsp) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRsp.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRsp) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{16}
}

type DelCategoryListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @ref_to: GetCategoryListReq.ListOption
	ListOption *lb.ListOption `protobuf:"bytes,1,opt,name=list_option,json=listOption,proto3" json:"list_option,omitempty"`
}

func (x *DelCategoryListReq) Reset() {
	*x = DelCategoryListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelCategoryListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelCategoryListReq) ProtoMessage() {}

func (x *DelCategoryListReq) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelCategoryListReq.ProtoReflect.Descriptor instead.
func (*DelCategoryListReq) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{17}
}

func (x *DelCategoryListReq) GetListOption() *lb.ListOption {
	if x != nil {
		return x.ListOption
	}
	return nil
}

type DelCategoryListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelCategoryListRsp) Reset() {
	*x = DelCategoryListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelCategoryListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelCategoryListRsp) ProtoMessage() {}

func (x *DelCategoryListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelCategoryListRsp.ProtoReflect.Descriptor instead.
func (*DelCategoryListRsp) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{18}
}

type GetCategoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCategoryReq) Reset() {
	*x = GetCategoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCategoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryReq) ProtoMessage() {}

func (x *GetCategoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryReq.ProtoReflect.Descriptor instead.
func (*GetCategoryReq) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{19}
}

func (x *GetCategoryReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCategoryRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelCategory `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetCategoryRsp) Reset() {
	*x = GetCategoryRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCategoryRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryRsp) ProtoMessage() {}

func (x *GetCategoryRsp) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryRsp.ProtoReflect.Descriptor instead.
func (*GetCategoryRsp) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{20}
}

func (x *GetCategoryRsp) GetData() *ModelCategory {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetCategoryListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListOption *lb.ListOption `protobuf:"bytes,1,opt,name=list_option,json=listOption,proto3" json:"list_option,omitempty"`
}

func (x *GetCategoryListReq) Reset() {
	*x = GetCategoryListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCategoryListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryListReq) ProtoMessage() {}

func (x *GetCategoryListReq) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryListReq.ProtoReflect.Descriptor instead.
func (*GetCategoryListReq) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{21}
}

func (x *GetCategoryListReq) GetListOption() *lb.ListOption {
	if x != nil {
		return x.ListOption
	}
	return nil
}

type GetCategoryListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paginate *lb.Paginate     `protobuf:"bytes,1,opt,name=paginate,proto3" json:"paginate,omitempty"`
	List     []*ModelCategory `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetCategoryListRsp) Reset() {
	*x = GetCategoryListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCategoryListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryListRsp) ProtoMessage() {}

func (x *GetCategoryListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryListRsp.ProtoReflect.Descriptor instead.
func (*GetCategoryListRsp) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{22}
}

func (x *GetCategoryListRsp) GetPaginate() *lb.Paginate {
	if x != nil {
		return x.Paginate
	}
	return nil
}

func (x *GetCategoryListRsp) GetList() []*ModelCategory {
	if x != nil {
		return x.List
	}
	return nil
}

type AddCommentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelComment `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddCommentReq) Reset() {
	*x = AddCommentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentReq) ProtoMessage() {}

func (x *AddCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentReq.ProtoReflect.Descriptor instead.
func (*AddCommentReq) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{23}
}

func (x *AddCommentReq) GetData() *ModelComment {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddCommentRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelComment `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AddCommentRsp) Reset() {
	*x = AddCommentRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCommentRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCommentRsp) ProtoMessage() {}

func (x *AddCommentRsp) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCommentRsp.ProtoReflect.Descriptor instead.
func (*AddCommentRsp) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{24}
}

func (x *AddCommentRsp) GetData() *ModelComment {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateCommentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelComment `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UpdateCommentReq) Reset() {
	*x = UpdateCommentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentReq) ProtoMessage() {}

func (x *UpdateCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentReq.ProtoReflect.Descriptor instead.
func (*UpdateCommentReq) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateCommentReq) GetData() *ModelComment {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateCommentRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateCommentRsp) Reset() {
	*x = UpdateCommentRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCommentRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRsp) ProtoMessage() {}

func (x *UpdateCommentRsp) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRsp.ProtoReflect.Descriptor instead.
func (*UpdateCommentRsp) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{26}
}

type DelCommentListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @ref_to: GetCommentListReq.ListOption
	ListOption *lb.ListOption `protobuf:"bytes,1,opt,name=list_option,json=listOption,proto3" json:"list_option,omitempty"`
}

func (x *DelCommentListReq) Reset() {
	*x = DelCommentListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelCommentListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelCommentListReq) ProtoMessage() {}

func (x *DelCommentListReq) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelCommentListReq.ProtoReflect.Descriptor instead.
func (*DelCommentListReq) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{27}
}

func (x *DelCommentListReq) GetListOption() *lb.ListOption {
	if x != nil {
		return x.ListOption
	}
	return nil
}

type DelCommentListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DelCommentListRsp) Reset() {
	*x = DelCommentListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelCommentListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelCommentListRsp) ProtoMessage() {}

func (x *DelCommentListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelCommentListRsp.ProtoReflect.Descriptor instead.
func (*DelCommentListRsp) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{28}
}

type GetCommentReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCommentReq) Reset() {
	*x = GetCommentReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentReq) ProtoMessage() {}

func (x *GetCommentReq) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentReq.ProtoReflect.Descriptor instead.
func (*GetCommentReq) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{29}
}

func (x *GetCommentReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCommentRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *ModelComment `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetCommentRsp) Reset() {
	*x = GetCommentRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommentRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentRsp) ProtoMessage() {}

func (x *GetCommentRsp) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentRsp.ProtoReflect.Descriptor instead.
func (*GetCommentRsp) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{30}
}

func (x *GetCommentRsp) GetData() *ModelComment {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetCommentListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListOption *lb.ListOption `protobuf:"bytes,1,opt,name=list_option,json=listOption,proto3" json:"list_option,omitempty"`
}

func (x *GetCommentListReq) Reset() {
	*x = GetCommentListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommentListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentListReq) ProtoMessage() {}

func (x *GetCommentListReq) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentListReq.ProtoReflect.Descriptor instead.
func (*GetCommentListReq) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{31}
}

func (x *GetCommentListReq) GetListOption() *lb.ListOption {
	if x != nil {
		return x.ListOption
	}
	return nil
}

type GetCommentListRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Paginate *lb.Paginate    `protobuf:"bytes,1,opt,name=paginate,proto3" json:"paginate,omitempty"`
	List     []*ModelComment `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *GetCommentListRsp) Reset() {
	*x = GetCommentListRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lbblog_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCommentListRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentListRsp) ProtoMessage() {}

func (x *GetCommentListRsp) ProtoReflect() protoreflect.Message {
	mi := &file_lbblog_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentListRsp.ProtoReflect.Descriptor instead.
func (*GetCommentListRsp) Descriptor() ([]byte, []int) {
	return file_lbblog_proto_rawDescGZIP(), []int{32}
}

func (x *GetCommentListRsp) GetPaginate() *lb.Paginate {
	if x != nil {
		return x.Paginate
	}
	return nil
}

func (x *GetCommentListRsp) GetList() []*ModelComment {
	if x != nil {
		return x.List
	}
	return nil
}

var File_lbblog_proto protoreflect.FileDescriptor

var file_lbblog_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x1a, 0x0e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x08, 0x6c, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x9c, 0x02, 0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x20,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xfa,
	0x42, 0x07, 0x72, 0x05, 0x10, 0x01, 0x18, 0xac, 0x02, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x1e, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a,
	0xfa, 0x42, 0x07, 0x72, 0x05, 0x10, 0x01, 0x18, 0x84, 0x07, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x12, 0x28, 0x0a, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x0a,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x6d,
	0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x69, 0x6d, 0x67, 0x12, 0x21, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22,
	0x9c, 0x01, 0x0a, 0x0d, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1e,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xfa, 0x42,
	0x07, 0x72, 0x05, 0x10, 0x01, 0x18, 0xac, 0x02, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xe7,
	0x02, 0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x26, 0x0a, 0x0a,
	0x61, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04,
	0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x09, 0x61, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x21, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x42, 0x07, 0xfa,
	0x42, 0x04, 0x72, 0x02, 0x10, 0x01, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e, 0x69, 0x6c, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c,
	0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x61,
	0x6b, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x10, 0x03, 0x22, 0x43, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x41,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67,
	0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x42, 0x08, 0xfa,
	0x42, 0x05, 0x8a, 0x01, 0x02, 0x10, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x39, 0x0a,
	0x0d, 0x41, 0x64, 0x64, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x73, 0x70, 0x12, 0x28,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c,
	0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x46, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x32, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x62, 0x62,
	0x6c, 0x6f, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x42, 0x08, 0xfa, 0x42, 0x05, 0x8a, 0x01, 0x02, 0x10, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x12, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x52, 0x73, 0x70, 0x22, 0x4e, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x39, 0x0a, 0x0b, 0x6c, 0x69, 0x73,
	0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6c, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x08,
	0xfa, 0x42, 0x05, 0x8a, 0x01, 0x02, 0x10, 0x01, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22, 0x28, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x52, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x9a,
	0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x39, 0x0a, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6c, 0x62, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x8a, 0x01,
	0x02, 0x10, 0x01, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x4a, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x11, 0x0a,
	0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x69, 0x6c, 0x10, 0x00,
	0x12, 0x14, 0x0a, 0x10, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x49, 0x64, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x69, 0x6b, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x10, 0x02, 0x22, 0x67, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70,
	0x12, 0x28, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x62, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65,
	0x52, 0x08, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f,
	0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x22, 0x45, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x33, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x42, 0x08, 0xfa, 0x42, 0x05,
	0x8a, 0x01, 0x02, 0x10, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3b, 0x0a, 0x0e, 0x41,
	0x64, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x73, 0x70, 0x12, 0x29, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x62,
	0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x48, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x33, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x62,
	0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x8a, 0x01, 0x02, 0x10, 0x01, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x52, 0x73, 0x70, 0x22, 0x4f, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x39, 0x0a,
	0x0b, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6c, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x8a, 0x01, 0x02, 0x10, 0x01, 0x52, 0x0a, 0x6c, 0x69,
	0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22, 0x29,
	0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x12, 0x17, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42,
	0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x73, 0x70, 0x12, 0x29, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x62, 0x62, 0x6c,
	0x6f, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x84, 0x01, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x39, 0x0a,
	0x0b, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6c, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x8a, 0x01, 0x02, 0x10, 0x01, 0x52, 0x0a, 0x6c, 0x69,
	0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x33, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x11, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x69, 0x6c, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x6b, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x10, 0x01, 0x22, 0x69, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x62, 0x2e, 0x50, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x65, 0x52, 0x08, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x29, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6c, 0x62,
	0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x43, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x43,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x32, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67,
	0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x08, 0xfa,
	0x42, 0x05, 0x8a, 0x01, 0x02, 0x10, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x39, 0x0a,
	0x0d, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x73, 0x70, 0x12, 0x28,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c,
	0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x46, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x32, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x62, 0x62,
	0x6c, 0x6f, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x42, 0x08, 0xfa, 0x42, 0x05, 0x8a, 0x01, 0x02, 0x10, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x12, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x73, 0x70, 0x22, 0x4e, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x39, 0x0a, 0x0b, 0x6c, 0x69, 0x73,
	0x74, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6c, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x08,
	0xfa, 0x42, 0x05, 0x8a, 0x01, 0x02, 0x10, 0x01, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22, 0x28, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xe0,
	0x01, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x39, 0x0a, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6c, 0x62, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x8a, 0x01,
	0x02, 0x10, 0x01, 0x52, 0x0a, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x8f, 0x01, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x11,
	0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x69, 0x6c, 0x10,
	0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x72, 0x74, 0x69, 0x63,
	0x6c, 0x65, 0x49, 0x64, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x4c, 0x69, 0x6b, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x10, 0x02, 0x12, 0x10, 0x0a,
	0x0c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x10, 0x03, 0x12,
	0x17, 0x0a, 0x13, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x6b, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x10, 0x04, 0x12, 0x17, 0x0a, 0x13, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x10,
	0x05, 0x22, 0x67, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x12, 0x28, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x62, 0x2e, 0x50, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x08, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x65,
	0x12, 0x28, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x2a, 0x61, 0x0a, 0x07, 0x45, 0x72,
	0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x4e, 0x69, 0x6c, 0x10, 0x00, 0x12, 0x18,
	0x0a, 0x12, 0x45, 0x72, 0x72, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4e, 0x6f, 0x74, 0x46,
	0x6f, 0x75, 0x6e, 0x64, 0x10, 0xc0, 0xb8, 0x02, 0x12, 0x19, 0x0a, 0x13, 0x45, 0x72, 0x72, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10,
	0xc1, 0xb8, 0x02, 0x12, 0x18, 0x0a, 0x12, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x10, 0xc2, 0xb8, 0x02, 0x32, 0xc4, 0x0a,
	0x0a, 0x06, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x12, 0x4e, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x41,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x15, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e,
	0x41, 0x64, 0x64, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e,
	0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x52, 0x73, 0x70, 0x22, 0x12, 0xa2, 0xe2, 0x09, 0x03, 0x61, 0x64, 0x64, 0xaa, 0xe2, 0x09,
	0x07, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x5d, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x41,
	0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x6c, 0x62, 0x62,
	0x6c, 0x6f, 0x67, 0x2e, 0x44, 0x65, 0x6c, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x44,
	0x65, 0x6c, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70,
	0x22, 0x15, 0xa2, 0xe2, 0x09, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0xaa, 0xe2, 0x09, 0x07,
	0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x5a, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x18, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f,
	0x67, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x18, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x73, 0x70, 0x22, 0x15, 0xa2, 0xe2,
	0x09, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0xaa, 0xe2, 0x09, 0x07, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x12, 0x4e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x12, 0x15, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72,
	0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f,
	0x67, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x73, 0x70, 0x22,
	0x12, 0xa2, 0xe2, 0x09, 0x03, 0x67, 0x65, 0x74, 0xaa, 0xe2, 0x09, 0x07, 0x41, 0x72, 0x74, 0x69,
	0x63, 0x6c, 0x65, 0x12, 0x5b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c,
	0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x19, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x74,
	0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22, 0x13, 0xa2, 0xe2, 0x09,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0xaa, 0xe2, 0x09, 0x07, 0x41, 0x72, 0x74, 0x69, 0x63, 0x6c, 0x65,
	0x12, 0x52, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12,
	0x16, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67,
	0x2e, 0x41, 0x64, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x73, 0x70, 0x22,
	0x13, 0xa2, 0xe2, 0x09, 0x03, 0x61, 0x64, 0x64, 0xaa, 0xe2, 0x09, 0x08, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x12, 0x61, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67,
	0x2e, 0x44, 0x65, 0x6c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x44, 0x65, 0x6c,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22,
	0x16, 0xa2, 0xe2, 0x09, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0xaa, 0xe2, 0x09, 0x08, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x5e, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x19, 0x2e, 0x6c, 0x62, 0x62, 0x6c,
	0x6f, 0x67, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x73, 0x70, 0x22,
	0x16, 0xa2, 0xe2, 0x09, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0xaa, 0xe2, 0x09, 0x08, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x52, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x16, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x16,
	0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x52, 0x73, 0x70, 0x22, 0x13, 0xa2, 0xe2, 0x09, 0x03, 0x67, 0x65, 0x74, 0xaa,
	0xe2, 0x09, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x5f, 0x0a, 0x0f, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1a,
	0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x6c, 0x62, 0x62,
	0x6c, 0x6f, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22, 0x14, 0xa2, 0xe2, 0x09, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0xaa, 0xe2, 0x09, 0x08, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x4e, 0x0a, 0x0a,
	0x41, 0x64, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x2e, 0x6c, 0x62, 0x62,
	0x6c, 0x6f, 0x67, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x15, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x73, 0x70, 0x22, 0x12, 0xa2, 0xe2, 0x09, 0x03, 0x61, 0x64,
	0x64, 0xaa, 0xe2, 0x09, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x5d, 0x0a, 0x0e,
	0x44, 0x65, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x19,
	0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x44, 0x65, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x6c, 0x62, 0x62, 0x6c,
	0x6f, 0x67, 0x2e, 0x44, 0x65, 0x6c, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x73, 0x70, 0x22, 0x15, 0xa2, 0xe2, 0x09, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0xaa, 0xe2, 0x09, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x5a, 0x0a, 0x0d, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x2e, 0x6c,
	0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x73, 0x70,
	0x22, 0x15, 0xa2, 0xe2, 0x09, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0xaa, 0xe2, 0x09, 0x07,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x4e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x15, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x6c,
	0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x73, 0x70, 0x22, 0x12, 0xa2, 0xe2, 0x09, 0x03, 0x67, 0x65, 0x74, 0xaa, 0xe2, 0x09, 0x07,
	0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x5b, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x19, 0x2e, 0x6c, 0x62, 0x62, 0x6c,
	0x6f, 0x67, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x73, 0x70, 0x22,
	0x13, 0xa2, 0xe2, 0x09, 0x04, 0x6c, 0x69, 0x73, 0x74, 0xaa, 0xe2, 0x09, 0x07, 0x43, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6f, 0x6c, 0x64, 0x62, 0x61, 0x69, 0x35, 0x35, 0x35, 0x2f, 0x62, 0x67, 0x67,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6c, 0x62, 0x62, 0x6c, 0x6f, 0x67, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lbblog_proto_rawDescOnce sync.Once
	file_lbblog_proto_rawDescData = file_lbblog_proto_rawDesc
)

func file_lbblog_proto_rawDescGZIP() []byte {
	file_lbblog_proto_rawDescOnce.Do(func() {
		file_lbblog_proto_rawDescData = protoimpl.X.CompressGZIP(file_lbblog_proto_rawDescData)
	})
	return file_lbblog_proto_rawDescData
}

var file_lbblog_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_lbblog_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_lbblog_proto_goTypes = []interface{}{
	(ErrCode)(0),                       // 0: lbblog.ErrCode
	(ModelComment_Status)(0),           // 1: lbblog.ModelComment.Status
	(GetArticleListReq_ListOption)(0),  // 2: lbblog.GetArticleListReq.ListOption
	(GetCategoryListReq_ListOption)(0), // 3: lbblog.GetCategoryListReq.ListOption
	(GetCommentListReq_ListOption)(0),  // 4: lbblog.GetCommentListReq.ListOption
	(*ModelArticle)(nil),               // 5: lbblog.ModelArticle
	(*ModelCategory)(nil),              // 6: lbblog.ModelCategory
	(*ModelComment)(nil),               // 7: lbblog.ModelComment
	(*AddArticleReq)(nil),              // 8: lbblog.AddArticleReq
	(*AddArticleRsp)(nil),              // 9: lbblog.AddArticleRsp
	(*UpdateArticleReq)(nil),           // 10: lbblog.UpdateArticleReq
	(*UpdateArticleRsp)(nil),           // 11: lbblog.UpdateArticleRsp
	(*DelArticleListReq)(nil),          // 12: lbblog.DelArticleListReq
	(*DelArticleListRsp)(nil),          // 13: lbblog.DelArticleListRsp
	(*GetArticleReq)(nil),              // 14: lbblog.GetArticleReq
	(*GetArticleRsp)(nil),              // 15: lbblog.GetArticleRsp
	(*GetArticleListReq)(nil),          // 16: lbblog.GetArticleListReq
	(*GetArticleListRsp)(nil),          // 17: lbblog.GetArticleListRsp
	(*AddCategoryReq)(nil),             // 18: lbblog.AddCategoryReq
	(*AddCategoryRsp)(nil),             // 19: lbblog.AddCategoryRsp
	(*UpdateCategoryReq)(nil),          // 20: lbblog.UpdateCategoryReq
	(*UpdateCategoryRsp)(nil),          // 21: lbblog.UpdateCategoryRsp
	(*DelCategoryListReq)(nil),         // 22: lbblog.DelCategoryListReq
	(*DelCategoryListRsp)(nil),         // 23: lbblog.DelCategoryListRsp
	(*GetCategoryReq)(nil),             // 24: lbblog.GetCategoryReq
	(*GetCategoryRsp)(nil),             // 25: lbblog.GetCategoryRsp
	(*GetCategoryListReq)(nil),         // 26: lbblog.GetCategoryListReq
	(*GetCategoryListRsp)(nil),         // 27: lbblog.GetCategoryListRsp
	(*AddCommentReq)(nil),              // 28: lbblog.AddCommentReq
	(*AddCommentRsp)(nil),              // 29: lbblog.AddCommentRsp
	(*UpdateCommentReq)(nil),           // 30: lbblog.UpdateCommentReq
	(*UpdateCommentRsp)(nil),           // 31: lbblog.UpdateCommentRsp
	(*DelCommentListReq)(nil),          // 32: lbblog.DelCommentListReq
	(*DelCommentListRsp)(nil),          // 33: lbblog.DelCommentListRsp
	(*GetCommentReq)(nil),              // 34: lbblog.GetCommentReq
	(*GetCommentRsp)(nil),              // 35: lbblog.GetCommentRsp
	(*GetCommentListReq)(nil),          // 36: lbblog.GetCommentListReq
	(*GetCommentListRsp)(nil),          // 37: lbblog.GetCommentListRsp
	(*lb.ListOption)(nil),              // 38: lb.ListOption
	(*lb.Paginate)(nil),                // 39: lb.Paginate
}
var file_lbblog_proto_depIdxs = []int32{
	5,  // 0: lbblog.AddArticleReq.data:type_name -> lbblog.ModelArticle
	5,  // 1: lbblog.AddArticleRsp.data:type_name -> lbblog.ModelArticle
	5,  // 2: lbblog.UpdateArticleReq.data:type_name -> lbblog.ModelArticle
	38, // 3: lbblog.DelArticleListReq.list_option:type_name -> lb.ListOption
	5,  // 4: lbblog.GetArticleRsp.data:type_name -> lbblog.ModelArticle
	38, // 5: lbblog.GetArticleListReq.list_option:type_name -> lb.ListOption
	39, // 6: lbblog.GetArticleListRsp.paginate:type_name -> lb.Paginate
	5,  // 7: lbblog.GetArticleListRsp.list:type_name -> lbblog.ModelArticle
	6,  // 8: lbblog.AddCategoryReq.data:type_name -> lbblog.ModelCategory
	6,  // 9: lbblog.AddCategoryRsp.data:type_name -> lbblog.ModelCategory
	6,  // 10: lbblog.UpdateCategoryReq.data:type_name -> lbblog.ModelCategory
	38, // 11: lbblog.DelCategoryListReq.list_option:type_name -> lb.ListOption
	6,  // 12: lbblog.GetCategoryRsp.data:type_name -> lbblog.ModelCategory
	38, // 13: lbblog.GetCategoryListReq.list_option:type_name -> lb.ListOption
	39, // 14: lbblog.GetCategoryListRsp.paginate:type_name -> lb.Paginate
	6,  // 15: lbblog.GetCategoryListRsp.list:type_name -> lbblog.ModelCategory
	7,  // 16: lbblog.AddCommentReq.data:type_name -> lbblog.ModelComment
	7,  // 17: lbblog.AddCommentRsp.data:type_name -> lbblog.ModelComment
	7,  // 18: lbblog.UpdateCommentReq.data:type_name -> lbblog.ModelComment
	38, // 19: lbblog.DelCommentListReq.list_option:type_name -> lb.ListOption
	7,  // 20: lbblog.GetCommentRsp.data:type_name -> lbblog.ModelComment
	38, // 21: lbblog.GetCommentListReq.list_option:type_name -> lb.ListOption
	39, // 22: lbblog.GetCommentListRsp.paginate:type_name -> lb.Paginate
	7,  // 23: lbblog.GetCommentListRsp.list:type_name -> lbblog.ModelComment
	8,  // 24: lbblog.lbblog.AddArticle:input_type -> lbblog.AddArticleReq
	12, // 25: lbblog.lbblog.DelArticleList:input_type -> lbblog.DelArticleListReq
	10, // 26: lbblog.lbblog.UpdateArticle:input_type -> lbblog.UpdateArticleReq
	14, // 27: lbblog.lbblog.GetArticle:input_type -> lbblog.GetArticleReq
	16, // 28: lbblog.lbblog.GetArticleList:input_type -> lbblog.GetArticleListReq
	18, // 29: lbblog.lbblog.AddCategory:input_type -> lbblog.AddCategoryReq
	22, // 30: lbblog.lbblog.DelCategoryList:input_type -> lbblog.DelCategoryListReq
	20, // 31: lbblog.lbblog.UpdateCategory:input_type -> lbblog.UpdateCategoryReq
	24, // 32: lbblog.lbblog.GetCategory:input_type -> lbblog.GetCategoryReq
	26, // 33: lbblog.lbblog.GetCategoryList:input_type -> lbblog.GetCategoryListReq
	28, // 34: lbblog.lbblog.AddComment:input_type -> lbblog.AddCommentReq
	32, // 35: lbblog.lbblog.DelCommentList:input_type -> lbblog.DelCommentListReq
	30, // 36: lbblog.lbblog.UpdateComment:input_type -> lbblog.UpdateCommentReq
	34, // 37: lbblog.lbblog.GetComment:input_type -> lbblog.GetCommentReq
	36, // 38: lbblog.lbblog.GetCommentList:input_type -> lbblog.GetCommentListReq
	9,  // 39: lbblog.lbblog.AddArticle:output_type -> lbblog.AddArticleRsp
	13, // 40: lbblog.lbblog.DelArticleList:output_type -> lbblog.DelArticleListRsp
	11, // 41: lbblog.lbblog.UpdateArticle:output_type -> lbblog.UpdateArticleRsp
	15, // 42: lbblog.lbblog.GetArticle:output_type -> lbblog.GetArticleRsp
	17, // 43: lbblog.lbblog.GetArticleList:output_type -> lbblog.GetArticleListRsp
	19, // 44: lbblog.lbblog.AddCategory:output_type -> lbblog.AddCategoryRsp
	23, // 45: lbblog.lbblog.DelCategoryList:output_type -> lbblog.DelCategoryListRsp
	21, // 46: lbblog.lbblog.UpdateCategory:output_type -> lbblog.UpdateCategoryRsp
	25, // 47: lbblog.lbblog.GetCategory:output_type -> lbblog.GetCategoryRsp
	27, // 48: lbblog.lbblog.GetCategoryList:output_type -> lbblog.GetCategoryListRsp
	29, // 49: lbblog.lbblog.AddComment:output_type -> lbblog.AddCommentRsp
	33, // 50: lbblog.lbblog.DelCommentList:output_type -> lbblog.DelCommentListRsp
	31, // 51: lbblog.lbblog.UpdateComment:output_type -> lbblog.UpdateCommentRsp
	35, // 52: lbblog.lbblog.GetComment:output_type -> lbblog.GetCommentRsp
	37, // 53: lbblog.lbblog.GetCommentList:output_type -> lbblog.GetCommentListRsp
	39, // [39:54] is the sub-list for method output_type
	24, // [24:39] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_lbblog_proto_init() }
func file_lbblog_proto_init() {
	if File_lbblog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lbblog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelArticle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelCategory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModelComment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddArticleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddArticleRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateArticleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateArticleRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelArticleListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelArticleListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArticleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArticleRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArticleListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetArticleListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCategoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCategoryRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCategoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCategoryRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelCategoryListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelCategoryListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCategoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCategoryRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCategoryListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCategoryListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCommentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCommentRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCommentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCommentRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelCommentListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelCommentListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommentReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommentRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommentListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lbblog_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCommentListRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lbblog_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lbblog_proto_goTypes,
		DependencyIndexes: file_lbblog_proto_depIdxs,
		EnumInfos:         file_lbblog_proto_enumTypes,
		MessageInfos:      file_lbblog_proto_msgTypes,
	}.Build()
	File_lbblog_proto = out.File
	file_lbblog_proto_rawDesc = nil
	file_lbblog_proto_goTypes = nil
	file_lbblog_proto_depIdxs = nil
}
