[program:m3u8]
directory=/home/work/m3u8
command=/home/work/m3u8/m3u8
autostart=true
autorestart=true
startsecs=10
startretries=3
user=root
redirect_stderr=true
stdout_logfile=/home/work/supervisor/logs/m3u8_stdout.log
stderr_logfile=/home/work/supervisor/logs/m3u8_stderr.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=20
