// Code generated by db_field_autogen.go, DO NOT EDIT.

package lbbill

const (
	DbAmount       = "amount"
	DbBill         = "bill"
	DbCategory     = "category"
	DbCategoryId   = "category_id"
	DbCategoryMap  = "category_map"
	DbCreatedAt    = "created_at"
	DbCreatorUid   = "creator_uid"
	DbDateUnix     = "date_unix"
	DbDeletedAt    = "deleted_at"
	DbId           = "id"
	DbList         = "list"
	DbName         = "name"
	DbOptions      = "options"
	DbPaginate     = "paginate"
	DbRemark       = "remark"
	DbRootCategory = "root_category"
	DbUpdatedAt    = "updated_at"
)
