// Code generated by mockery v2.53.6. DO NOT EDIT.

package chat_mocks

import (
	context "context"
	chat "postapocgame/admin-server/internal/domain/chat"

	mock "github.com/stretchr/testify/mock"
)

// UserLister is an autogenerated mock type for the UserLister type
type UserLister struct {
	mock.Mock
}

// FindChunk provides a mock function with given fields: ctx, limit, lastID
func (_m *UserLister) FindChunk(ctx context.Context, limit int, lastID uint64) ([]chat.UserRef, uint64, error) {
	ret := _m.Called(ctx, limit, lastID)

	if len(ret) == 0 {
		panic("no return value specified for FindChunk")
	}

	var r0 []chat.UserRef
	var r1 uint64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, uint64) ([]chat.UserRef, uint64, error)); ok {
		return rf(ctx, limit, lastID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, uint64) []chat.UserRef); ok {
		r0 = rf(ctx, limit, lastID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]chat.UserRef)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, uint64) uint64); ok {
		r1 = rf(ctx, limit, lastID)
	} else {
		r1 = ret.Get(1).(uint64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, uint64) error); ok {
		r2 = rf(ctx, limit, lastID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewUserLister creates a new instance of UserLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserLister {
	mock := &UserLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
