// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.11
// source: lbconst.proto

package lbconst

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LbconstClient is the client API for Lbconst service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LbconstClient interface {
}

type lbconstClient struct {
	cc grpc.ClientConnInterface
}

func NewLbconstClient(cc grpc.ClientConnInterface) LbconstClient {
	return &lbconstClient{cc}
}

// LbconstServer is the server API for Lbconst service.
// All implementations must embed UnimplementedLbconstServer
// for forward compatibility
type LbconstServer interface {
	mustEmbedUnimplementedLbconstServer()
}

// UnimplementedLbconstServer must be embedded to have forward compatible implementations.
type UnimplementedLbconstServer struct {
}

func (UnimplementedLbconstServer) mustEmbedUnimplementedLbconstServer() {}

// UnsafeLbconstServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LbconstServer will
// result in compilation errors.
type UnsafeLbconstServer interface {
	mustEmbedUnimplementedLbconstServer()
}

func RegisterLbconstServer(s grpc.ServiceRegistrar, srv LbconstServer) {
	s.RegisterService(&Lbconst_ServiceDesc, srv)
}

// Lbconst_ServiceDesc is the grpc.ServiceDesc for Lbconst service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lbconst_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lbconst.lbconst",
	HandlerType: (*LbconstServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "lbconst.proto",
}
