// Code generated by baixctl genclient. DO NOT EDIT.
package lbwechat

import (
	"context"
)

const ClientName = "lbwechat"

func HandleWxGzhAuth(ctx context.Context, req *HandleWxGzhAuthReq) (*HandleWxGzhAuthRsp, error) {
	if cliMgr.conn == nil {
		return nil, cliMgr.Err
	}
	return cliMgr.cli.HandleWxGzhAuth(ctx, req)
}

func HandleWxGzhMsg(ctx context.Context, req *HandleWxGzhMsgReq) (*HandleWxGzhMsgRsp, error) {
	if cliMgr.conn == nil {
		return nil, cliMgr.Err
	}
	return cliMgr.cli.HandleWxGzhMsg(ctx, req)
}
