// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: iam.proto

package iamclient

import (
	"context"

	"postapocgame/admin-server/services/iam/iam"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApiCreateRequest                = iam.ApiCreateRequest
	ApiDeleteRequest                = iam.ApiDeleteRequest
	ApiItem                         = iam.ApiItem
	ApiListRequest                  = iam.ApiListRequest
	ApiListResponse                 = iam.ApiListResponse
	ApiRouteRef                     = iam.ApiRouteRef
	ApiUpdateRequest                = iam.ApiUpdateRequest
	AuditLogDetailRequest           = iam.AuditLogDetailRequest
	AuditLogItem                    = iam.AuditLogItem
	AuditLogListRequest             = iam.AuditLogListRequest
	AuditLogListResponse            = iam.AuditLogListResponse
	BatchRecordOperationLogRequest  = iam.BatchRecordOperationLogRequest
	CheckApiEnabledRequest          = iam.CheckApiEnabledRequest
	CheckApiEnabledResponse         = iam.CheckApiEnabledResponse
	CheckPermissionRequest          = iam.CheckPermissionRequest
	CheckPermissionResponse         = iam.CheckPermissionResponse
	ConfigCreateRequest             = iam.ConfigCreateRequest
	ConfigDeleteRequest             = iam.ConfigDeleteRequest
	ConfigGetRequest                = iam.ConfigGetRequest
	ConfigGetResponse               = iam.ConfigGetResponse
	ConfigItem                      = iam.ConfigItem
	ConfigListRequest               = iam.ConfigListRequest
	ConfigListResponse              = iam.ConfigListResponse
	ConfigUpdateRequest             = iam.ConfigUpdateRequest
	DailyShortSentenceCreateRequest = iam.DailyShortSentenceCreateRequest
	DailyShortSentenceDeleteRequest = iam.DailyShortSentenceDeleteRequest
	DailyShortSentenceItem          = iam.DailyShortSentenceItem
	DailyShortSentenceListRequest   = iam.DailyShortSentenceListRequest
	DailyShortSentenceListResponse  = iam.DailyShortSentenceListResponse
	DailyShortSentenceUpdateRequest = iam.DailyShortSentenceUpdateRequest
	DemoCreateRequest               = iam.DemoCreateRequest
	DemoDeleteRequest               = iam.DemoDeleteRequest
	DemoItem                        = iam.DemoItem
	DemoListRequest                 = iam.DemoListRequest
	DemoListResponse                = iam.DemoListResponse
	DemoUpdateRequest               = iam.DemoUpdateRequest
	DepartmentCreateRequest         = iam.DepartmentCreateRequest
	DepartmentDeleteRequest         = iam.DepartmentDeleteRequest
	DepartmentItem                  = iam.DepartmentItem
	DepartmentTreeResponse          = iam.DepartmentTreeResponse
	DepartmentUpdateRequest         = iam.DepartmentUpdateRequest
	DictBatchGetRequest             = iam.DictBatchGetRequest
	DictBatchGetResponse            = iam.DictBatchGetResponse
	DictGetRequest                  = iam.DictGetRequest
	DictGetResponse                 = iam.DictGetResponse
	DictItemCreateRequest           = iam.DictItemCreateRequest
	DictItemDeleteRequest           = iam.DictItemDeleteRequest
	DictItemItem                    = iam.DictItemItem
	DictItemListRequest             = iam.DictItemListRequest
	DictItemListResponse            = iam.DictItemListResponse
	DictItemUpdateRequest           = iam.DictItemUpdateRequest
	DictTypeCreateRequest           = iam.DictTypeCreateRequest
	DictTypeDeleteRequest           = iam.DictTypeDeleteRequest
	DictTypeItem                    = iam.DictTypeItem
	DictTypeListRequest             = iam.DictTypeListRequest
	DictTypeListResponse            = iam.DictTypeListResponse
	DictTypeUpdateRequest           = iam.DictTypeUpdateRequest
	Empty                           = iam.Empty
	FileCreateRequest               = iam.FileCreateRequest
	FileDeleteRequest               = iam.FileDeleteRequest
	FileGetMetaRequest              = iam.FileGetMetaRequest
	FileGetMetaResponse             = iam.FileGetMetaResponse
	FileItem                        = iam.FileItem
	FileListRequest                 = iam.FileListRequest
	FileListResponse                = iam.FileListResponse
	FileRegisterRequest             = iam.FileRegisterRequest
	FileRegisterResponse            = iam.FileRegisterResponse
	FileUpdateRequest               = iam.FileUpdateRequest
	LoginFeishuRequest              = iam.LoginFeishuRequest
	LoginLogDetailRequest           = iam.LoginLogDetailRequest
	LoginLogItem                    = iam.LoginLogItem
	LoginLogListRequest             = iam.LoginLogListRequest
	LoginLogListResponse            = iam.LoginLogListResponse
	LoginLogStatsResponse           = iam.LoginLogStatsResponse
	LoginRequest                    = iam.LoginRequest
	LogoutRequest                   = iam.LogoutRequest
	MenuCreateRequest               = iam.MenuCreateRequest
	MenuDeleteRequest               = iam.MenuDeleteRequest
	MenuItem                        = iam.MenuItem
	MenuMyTreeRequest               = iam.MenuMyTreeRequest
	MenuTreeResponse                = iam.MenuTreeResponse
	MenuUpdateRequest               = iam.MenuUpdateRequest
	MetricReportRequest             = iam.MetricReportRequest
	MetricStatsRequest              = iam.MetricStatsRequest
	MetricStatsResponse             = iam.MetricStatsResponse
	MonitorStatsResponse            = iam.MonitorStatsResponse
	MonitorStatusResponse           = iam.MonitorStatusResponse
	NoticeCreateRequest             = iam.NoticeCreateRequest
	NoticeDeleteRequest             = iam.NoticeDeleteRequest
	NoticeItem                      = iam.NoticeItem
	NoticeListRequest               = iam.NoticeListRequest
	NoticeListResponse              = iam.NoticeListResponse
	NoticeUpdateRequest             = iam.NoticeUpdateRequest
	NotificationClearReadRequest    = iam.NotificationClearReadRequest
	NotificationDeleteRequest       = iam.NotificationDeleteRequest
	NotificationItem                = iam.NotificationItem
	NotificationListRequest         = iam.NotificationListRequest
	NotificationListResponse        = iam.NotificationListResponse
	NotificationReadAllRequest      = iam.NotificationReadAllRequest
	NotificationReadRequest         = iam.NotificationReadRequest
	OperationLogDetailRequest       = iam.OperationLogDetailRequest
	OperationLogEntry               = iam.OperationLogEntry
	OperationLogItem                = iam.OperationLogItem
	OperationLogListRequest         = iam.OperationLogListRequest
	OperationLogListResponse        = iam.OperationLogListResponse
	PasswordChangeRequest           = iam.PasswordChangeRequest
	PerformanceLogItem              = iam.PerformanceLogItem
	PerformanceLogListRequest       = iam.PerformanceLogListRequest
	PerformanceLogListResponse      = iam.PerformanceLogListResponse
	PermissionApiListRequest        = iam.PermissionApiListRequest
	PermissionApiListResponse       = iam.PermissionApiListResponse
	PermissionApiUpdateRequest      = iam.PermissionApiUpdateRequest
	PermissionCreateRequest         = iam.PermissionCreateRequest
	PermissionDeleteRequest         = iam.PermissionDeleteRequest
	PermissionItem                  = iam.PermissionItem
	PermissionListRequest           = iam.PermissionListRequest
	PermissionListResponse          = iam.PermissionListResponse
	PermissionMenuListRequest       = iam.PermissionMenuListRequest
	PermissionMenuListResponse      = iam.PermissionMenuListResponse
	PermissionMenuUpdateRequest     = iam.PermissionMenuUpdateRequest
	PermissionUpdateRequest         = iam.PermissionUpdateRequest
	PingResponse                    = iam.PingResponse
	ProfileRequest                  = iam.ProfileRequest
	ProfileResponse                 = iam.ProfileResponse
	ProfileUpdateRequest            = iam.ProfileUpdateRequest
	RecordPerformanceLogRequest     = iam.RecordPerformanceLogRequest
	RefreshRequest                  = iam.RefreshRequest
	RoleCreateRequest               = iam.RoleCreateRequest
	RoleDeleteRequest               = iam.RoleDeleteRequest
	RoleItem                        = iam.RoleItem
	RoleListRequest                 = iam.RoleListRequest
	RoleListResponse                = iam.RoleListResponse
	RolePermissionListRequest       = iam.RolePermissionListRequest
	RolePermissionListResponse      = iam.RolePermissionListResponse
	RolePermissionUpdateRequest     = iam.RolePermissionUpdateRequest
	RoleUpdateRequest               = iam.RoleUpdateRequest
	SyncApiRoutesRequest            = iam.SyncApiRoutesRequest
	TokenPair                       = iam.TokenPair
	UserCreateRequest               = iam.UserCreateRequest
	UserDeleteRequest               = iam.UserDeleteRequest
	UserItem                        = iam.UserItem
	UserListRequest                 = iam.UserListRequest
	UserListResponse                = iam.UserListResponse
	UserRoleListRequest             = iam.UserRoleListRequest
	UserRoleListResponse            = iam.UserRoleListResponse
	UserRoleUpdateRequest           = iam.UserRoleUpdateRequest
	UserUpdateRequest               = iam.UserUpdateRequest

	Iam interface {
		// 权限校验（GetUserProfile 等见 pkg/iamcallback.IamCallback，同一进程内另注册）
		CheckPermission(ctx context.Context, in *CheckPermissionRequest, opts ...grpc.CallOption) (*CheckPermissionResponse, error)
		// Gateway 基础设施
		CheckApiEnabled(ctx context.Context, in *CheckApiEnabledRequest, opts ...grpc.CallOption) (*CheckApiEnabledResponse, error)
		SyncApiRoutes(ctx context.Context, in *SyncApiRoutesRequest, opts ...grpc.CallOption) (*Empty, error)
		BatchRecordOperationLog(ctx context.Context, in *BatchRecordOperationLogRequest, opts ...grpc.CallOption) (*Empty, error)
		RecordPerformanceLog(ctx context.Context, in *RecordPerformanceLogRequest, opts ...grpc.CallOption) (*Empty, error)
		FileRegister(ctx context.Context, in *FileRegisterRequest, opts ...grpc.CallOption) (*FileRegisterResponse, error)
		FileGetMeta(ctx context.Context, in *FileGetMetaRequest, opts ...grpc.CallOption) (*FileGetMetaResponse, error)
		Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResponse, error)
		// Auth
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*TokenPair, error)
		LoginFeishu(ctx context.Context, in *LoginFeishuRequest, opts ...grpc.CallOption) (*TokenPair, error)
		Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*TokenPair, error)
		Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*Empty, error)
		Profile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error)
		ProfileUpdate(ctx context.Context, in *ProfileUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
		PasswordChange(ctx context.Context, in *PasswordChangeRequest, opts ...grpc.CallOption) (*Empty, error)
		// User / Role / Permission / Menu / Department / Api
		UserCreate(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*Empty, error)
		UserUpdate(ctx context.Context, in *UserUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
		UserDelete(ctx context.Context, in *UserDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
		UserList(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error)
		RoleCreate(ctx context.Context, in *RoleCreateRequest, opts ...grpc.CallOption) (*Empty, error)
		RoleUpdate(ctx context.Context, in *RoleUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
		RoleDelete(ctx context.Context, in *RoleDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
		RoleList(ctx context.Context, in *RoleListRequest, opts ...grpc.CallOption) (*RoleListResponse, error)
		PermissionCreate(ctx context.Context, in *PermissionCreateRequest, opts ...grpc.CallOption) (*Empty, error)
		PermissionUpdate(ctx context.Context, in *PermissionUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
		PermissionDelete(ctx context.Context, in *PermissionDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
		PermissionList(ctx context.Context, in *PermissionListRequest, opts ...grpc.CallOption) (*PermissionListResponse, error)
		MenuCreate(ctx context.Context, in *MenuCreateRequest, opts ...grpc.CallOption) (*Empty, error)
		MenuUpdate(ctx context.Context, in *MenuUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
		MenuDelete(ctx context.Context, in *MenuDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
		MenuTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MenuTreeResponse, error)
		MenuMyTree(ctx context.Context, in *MenuMyTreeRequest, opts ...grpc.CallOption) (*MenuTreeResponse, error)
		DepartmentCreate(ctx context.Context, in *DepartmentCreateRequest, opts ...grpc.CallOption) (*Empty, error)
		DepartmentUpdate(ctx context.Context, in *DepartmentUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
		DepartmentDelete(ctx context.Context, in *DepartmentDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
		DepartmentTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DepartmentTreeResponse, error)
		ApiCreate(ctx context.Context, in *ApiCreateRequest, opts ...grpc.CallOption) (*Empty, error)
		ApiUpdate(ctx context.Context, in *ApiUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
		ApiDelete(ctx context.Context, in *ApiDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
		ApiList(ctx context.Context, in *ApiListRequest, opts ...grpc.CallOption) (*ApiListResponse, error)
		// RBAC 关联关系
		PermissionMenuList(ctx context.Context, in *PermissionMenuListRequest, opts ...grpc.CallOption) (*PermissionMenuListResponse, error)
		PermissionMenuUpdate(ctx context.Context, in *PermissionMenuUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
		PermissionApiList(ctx context.Context, in *PermissionApiListRequest, opts ...grpc.CallOption) (*PermissionApiListResponse, error)
		PermissionApiUpdate(ctx context.Context, in *PermissionApiUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
		UserRoleList(ctx context.Context, in *UserRoleListRequest, opts ...grpc.CallOption) (*UserRoleListResponse, error)
		UserRoleUpdate(ctx context.Context, in *UserRoleUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
		RolePermissionList(ctx context.Context, in *RolePermissionListRequest, opts ...grpc.CallOption) (*RolePermissionListResponse, error)
		RolePermissionUpdate(ctx context.Context, in *RolePermissionUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
		// Config / Dict
		ConfigCreate(ctx context.Context, in *ConfigCreateRequest, opts ...grpc.CallOption) (*Empty, error)
		ConfigUpdate(ctx context.Context, in *ConfigUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
		ConfigDelete(ctx context.Context, in *ConfigDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
		ConfigList(ctx context.Context, in *ConfigListRequest, opts ...grpc.CallOption) (*ConfigListResponse, error)
		ConfigGet(ctx context.Context, in *ConfigGetRequest, opts ...grpc.CallOption) (*ConfigGetResponse, error)
		DictTypeCreate(ctx context.Context, in *DictTypeCreateRequest, opts ...grpc.CallOption) (*Empty, error)
		DictTypeUpdate(ctx context.Context, in *DictTypeUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
		DictTypeDelete(ctx context.Context, in *DictTypeDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
		DictTypeList(ctx context.Context, in *DictTypeListRequest, opts ...grpc.CallOption) (*DictTypeListResponse, error)
		DictItemCreate(ctx context.Context, in *DictItemCreateRequest, opts ...grpc.CallOption) (*Empty, error)
		DictItemUpdate(ctx context.Context, in *DictItemUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
		DictItemDelete(ctx context.Context, in *DictItemDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
		DictItemList(ctx context.Context, in *DictItemListRequest, opts ...grpc.CallOption) (*DictItemListResponse, error)
		DictGet(ctx context.Context, in *DictGetRequest, opts ...grpc.CallOption) (*DictGetResponse, error)
		DictBatchGet(ctx context.Context, in *DictBatchGetRequest, opts ...grpc.CallOption) (*DictBatchGetResponse, error)
		// File
		FileCreate(ctx context.Context, in *FileCreateRequest, opts ...grpc.CallOption) (*Empty, error)
		FileUpdate(ctx context.Context, in *FileUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
		FileDelete(ctx context.Context, in *FileDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
		FileList(ctx context.Context, in *FileListRequest, opts ...grpc.CallOption) (*FileListResponse, error)
		// Notice / Notification
		NoticeCreate(ctx context.Context, in *NoticeCreateRequest, opts ...grpc.CallOption) (*Empty, error)
		NoticeUpdate(ctx context.Context, in *NoticeUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
		NoticeDelete(ctx context.Context, in *NoticeDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
		NoticeList(ctx context.Context, in *NoticeListRequest, opts ...grpc.CallOption) (*NoticeListResponse, error)
		NotificationList(ctx context.Context, in *NotificationListRequest, opts ...grpc.CallOption) (*NotificationListResponse, error)
		NotificationRead(ctx context.Context, in *NotificationReadRequest, opts ...grpc.CallOption) (*Empty, error)
		NotificationReadAll(ctx context.Context, in *NotificationReadAllRequest, opts ...grpc.CallOption) (*Empty, error)
		NotificationClearRead(ctx context.Context, in *NotificationClearReadRequest, opts ...grpc.CallOption) (*Empty, error)
		NotificationDelete(ctx context.Context, in *NotificationDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
		// OperationLog / LoginLog / PerformanceLog / AuditLog（列表/详情/统计；导出见
		OperationLogList(ctx context.Context, in *OperationLogListRequest, opts ...grpc.CallOption) (*OperationLogListResponse, error)
		OperationLogDetail(ctx context.Context, in *OperationLogDetailRequest, opts ...grpc.CallOption) (*OperationLogItem, error)
		LoginLogList(ctx context.Context, in *LoginLogListRequest, opts ...grpc.CallOption) (*LoginLogListResponse, error)
		LoginLogDetail(ctx context.Context, in *LoginLogDetailRequest, opts ...grpc.CallOption) (*LoginLogItem, error)
		LoginLogStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LoginLogStatsResponse, error)
		PerformanceLogList(ctx context.Context, in *PerformanceLogListRequest, opts ...grpc.CallOption) (*PerformanceLogListResponse, error)
		AuditLogList(ctx context.Context, in *AuditLogListRequest, opts ...grpc.CallOption) (*AuditLogListResponse, error)
		AuditLogDetail(ctx context.Context, in *AuditLogDetailRequest, opts ...grpc.CallOption) (*AuditLogItem, error)
		// Metric / Monitor
		MetricReport(ctx context.Context, in *MetricReportRequest, opts ...grpc.CallOption) (*Empty, error)
		MetricStats(ctx context.Context, in *MetricStatsRequest, opts ...grpc.CallOption) (*MetricStatsResponse, error)
		MonitorStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MonitorStatsResponse, error)
		MonitorStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MonitorStatusResponse, error)
		// Demo / DailyShortSentence
		DemoCreate(ctx context.Context, in *DemoCreateRequest, opts ...grpc.CallOption) (*Empty, error)
		DemoUpdate(ctx context.Context, in *DemoUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
		DemoDelete(ctx context.Context, in *DemoDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
		DemoList(ctx context.Context, in *DemoListRequest, opts ...grpc.CallOption) (*DemoListResponse, error)
		DailyShortSentenceCreate(ctx context.Context, in *DailyShortSentenceCreateRequest, opts ...grpc.CallOption) (*Empty, error)
		DailyShortSentenceUpdate(ctx context.Context, in *DailyShortSentenceUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
		DailyShortSentenceDelete(ctx context.Context, in *DailyShortSentenceDeleteRequest, opts ...grpc.CallOption) (*Empty, error)
		DailyShortSentenceList(ctx context.Context, in *DailyShortSentenceListRequest, opts ...grpc.CallOption) (*DailyShortSentenceListResponse, error)
	}

	defaultIam struct {
		cli zrpc.Client
	}
)

func NewIam(cli zrpc.Client) Iam {
	return &defaultIam{
		cli: cli,
	}
}

// 权限校验（GetUserProfile 等见 pkg/iamcallback.IamCallback，同一进程内另注册）
func (m *defaultIam) CheckPermission(ctx context.Context, in *CheckPermissionRequest, opts ...grpc.CallOption) (*CheckPermissionResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.CheckPermission(ctx, in, opts...)
}

// Gateway 基础设施
func (m *defaultIam) CheckApiEnabled(ctx context.Context, in *CheckApiEnabledRequest, opts ...grpc.CallOption) (*CheckApiEnabledResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.CheckApiEnabled(ctx, in, opts...)
}

func (m *defaultIam) SyncApiRoutes(ctx context.Context, in *SyncApiRoutesRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.SyncApiRoutes(ctx, in, opts...)
}

func (m *defaultIam) BatchRecordOperationLog(ctx context.Context, in *BatchRecordOperationLogRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.BatchRecordOperationLog(ctx, in, opts...)
}

func (m *defaultIam) RecordPerformanceLog(ctx context.Context, in *RecordPerformanceLogRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.RecordPerformanceLog(ctx, in, opts...)
}

func (m *defaultIam) FileRegister(ctx context.Context, in *FileRegisterRequest, opts ...grpc.CallOption) (*FileRegisterResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.FileRegister(ctx, in, opts...)
}

func (m *defaultIam) FileGetMeta(ctx context.Context, in *FileGetMetaRequest, opts ...grpc.CallOption) (*FileGetMetaResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.FileGetMeta(ctx, in, opts...)
}

func (m *defaultIam) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

// Auth
func (m *defaultIam) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*TokenPair, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultIam) LoginFeishu(ctx context.Context, in *LoginFeishuRequest, opts ...grpc.CallOption) (*TokenPair, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.LoginFeishu(ctx, in, opts...)
}

func (m *defaultIam) Refresh(ctx context.Context, in *RefreshRequest, opts ...grpc.CallOption) (*TokenPair, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.Refresh(ctx, in, opts...)
}

func (m *defaultIam) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

func (m *defaultIam) Profile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*ProfileResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.Profile(ctx, in, opts...)
}

func (m *defaultIam) ProfileUpdate(ctx context.Context, in *ProfileUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.ProfileUpdate(ctx, in, opts...)
}

func (m *defaultIam) PasswordChange(ctx context.Context, in *PasswordChangeRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.PasswordChange(ctx, in, opts...)
}

// User / Role / Permission / Menu / Department / Api
func (m *defaultIam) UserCreate(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.UserCreate(ctx, in, opts...)
}

func (m *defaultIam) UserUpdate(ctx context.Context, in *UserUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.UserUpdate(ctx, in, opts...)
}

func (m *defaultIam) UserDelete(ctx context.Context, in *UserDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.UserDelete(ctx, in, opts...)
}

func (m *defaultIam) UserList(ctx context.Context, in *UserListRequest, opts ...grpc.CallOption) (*UserListResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.UserList(ctx, in, opts...)
}

func (m *defaultIam) RoleCreate(ctx context.Context, in *RoleCreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.RoleCreate(ctx, in, opts...)
}

func (m *defaultIam) RoleUpdate(ctx context.Context, in *RoleUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.RoleUpdate(ctx, in, opts...)
}

func (m *defaultIam) RoleDelete(ctx context.Context, in *RoleDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.RoleDelete(ctx, in, opts...)
}

func (m *defaultIam) RoleList(ctx context.Context, in *RoleListRequest, opts ...grpc.CallOption) (*RoleListResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.RoleList(ctx, in, opts...)
}

func (m *defaultIam) PermissionCreate(ctx context.Context, in *PermissionCreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.PermissionCreate(ctx, in, opts...)
}

func (m *defaultIam) PermissionUpdate(ctx context.Context, in *PermissionUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.PermissionUpdate(ctx, in, opts...)
}

func (m *defaultIam) PermissionDelete(ctx context.Context, in *PermissionDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.PermissionDelete(ctx, in, opts...)
}

func (m *defaultIam) PermissionList(ctx context.Context, in *PermissionListRequest, opts ...grpc.CallOption) (*PermissionListResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.PermissionList(ctx, in, opts...)
}

func (m *defaultIam) MenuCreate(ctx context.Context, in *MenuCreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.MenuCreate(ctx, in, opts...)
}

func (m *defaultIam) MenuUpdate(ctx context.Context, in *MenuUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.MenuUpdate(ctx, in, opts...)
}

func (m *defaultIam) MenuDelete(ctx context.Context, in *MenuDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.MenuDelete(ctx, in, opts...)
}

func (m *defaultIam) MenuTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MenuTreeResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.MenuTree(ctx, in, opts...)
}

func (m *defaultIam) MenuMyTree(ctx context.Context, in *MenuMyTreeRequest, opts ...grpc.CallOption) (*MenuTreeResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.MenuMyTree(ctx, in, opts...)
}

func (m *defaultIam) DepartmentCreate(ctx context.Context, in *DepartmentCreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DepartmentCreate(ctx, in, opts...)
}

func (m *defaultIam) DepartmentUpdate(ctx context.Context, in *DepartmentUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DepartmentUpdate(ctx, in, opts...)
}

func (m *defaultIam) DepartmentDelete(ctx context.Context, in *DepartmentDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DepartmentDelete(ctx, in, opts...)
}

func (m *defaultIam) DepartmentTree(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DepartmentTreeResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DepartmentTree(ctx, in, opts...)
}

func (m *defaultIam) ApiCreate(ctx context.Context, in *ApiCreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.ApiCreate(ctx, in, opts...)
}

func (m *defaultIam) ApiUpdate(ctx context.Context, in *ApiUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.ApiUpdate(ctx, in, opts...)
}

func (m *defaultIam) ApiDelete(ctx context.Context, in *ApiDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.ApiDelete(ctx, in, opts...)
}

func (m *defaultIam) ApiList(ctx context.Context, in *ApiListRequest, opts ...grpc.CallOption) (*ApiListResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.ApiList(ctx, in, opts...)
}

// RBAC 关联关系
func (m *defaultIam) PermissionMenuList(ctx context.Context, in *PermissionMenuListRequest, opts ...grpc.CallOption) (*PermissionMenuListResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.PermissionMenuList(ctx, in, opts...)
}

func (m *defaultIam) PermissionMenuUpdate(ctx context.Context, in *PermissionMenuUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.PermissionMenuUpdate(ctx, in, opts...)
}

func (m *defaultIam) PermissionApiList(ctx context.Context, in *PermissionApiListRequest, opts ...grpc.CallOption) (*PermissionApiListResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.PermissionApiList(ctx, in, opts...)
}

func (m *defaultIam) PermissionApiUpdate(ctx context.Context, in *PermissionApiUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.PermissionApiUpdate(ctx, in, opts...)
}

func (m *defaultIam) UserRoleList(ctx context.Context, in *UserRoleListRequest, opts ...grpc.CallOption) (*UserRoleListResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.UserRoleList(ctx, in, opts...)
}

func (m *defaultIam) UserRoleUpdate(ctx context.Context, in *UserRoleUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.UserRoleUpdate(ctx, in, opts...)
}

func (m *defaultIam) RolePermissionList(ctx context.Context, in *RolePermissionListRequest, opts ...grpc.CallOption) (*RolePermissionListResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.RolePermissionList(ctx, in, opts...)
}

func (m *defaultIam) RolePermissionUpdate(ctx context.Context, in *RolePermissionUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.RolePermissionUpdate(ctx, in, opts...)
}

// Config / Dict
func (m *defaultIam) ConfigCreate(ctx context.Context, in *ConfigCreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.ConfigCreate(ctx, in, opts...)
}

func (m *defaultIam) ConfigUpdate(ctx context.Context, in *ConfigUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.ConfigUpdate(ctx, in, opts...)
}

func (m *defaultIam) ConfigDelete(ctx context.Context, in *ConfigDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.ConfigDelete(ctx, in, opts...)
}

func (m *defaultIam) ConfigList(ctx context.Context, in *ConfigListRequest, opts ...grpc.CallOption) (*ConfigListResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.ConfigList(ctx, in, opts...)
}

func (m *defaultIam) ConfigGet(ctx context.Context, in *ConfigGetRequest, opts ...grpc.CallOption) (*ConfigGetResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.ConfigGet(ctx, in, opts...)
}

func (m *defaultIam) DictTypeCreate(ctx context.Context, in *DictTypeCreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DictTypeCreate(ctx, in, opts...)
}

func (m *defaultIam) DictTypeUpdate(ctx context.Context, in *DictTypeUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DictTypeUpdate(ctx, in, opts...)
}

func (m *defaultIam) DictTypeDelete(ctx context.Context, in *DictTypeDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DictTypeDelete(ctx, in, opts...)
}

func (m *defaultIam) DictTypeList(ctx context.Context, in *DictTypeListRequest, opts ...grpc.CallOption) (*DictTypeListResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DictTypeList(ctx, in, opts...)
}

func (m *defaultIam) DictItemCreate(ctx context.Context, in *DictItemCreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DictItemCreate(ctx, in, opts...)
}

func (m *defaultIam) DictItemUpdate(ctx context.Context, in *DictItemUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DictItemUpdate(ctx, in, opts...)
}

func (m *defaultIam) DictItemDelete(ctx context.Context, in *DictItemDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DictItemDelete(ctx, in, opts...)
}

func (m *defaultIam) DictItemList(ctx context.Context, in *DictItemListRequest, opts ...grpc.CallOption) (*DictItemListResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DictItemList(ctx, in, opts...)
}

func (m *defaultIam) DictGet(ctx context.Context, in *DictGetRequest, opts ...grpc.CallOption) (*DictGetResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DictGet(ctx, in, opts...)
}

func (m *defaultIam) DictBatchGet(ctx context.Context, in *DictBatchGetRequest, opts ...grpc.CallOption) (*DictBatchGetResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DictBatchGet(ctx, in, opts...)
}

// File
func (m *defaultIam) FileCreate(ctx context.Context, in *FileCreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.FileCreate(ctx, in, opts...)
}

func (m *defaultIam) FileUpdate(ctx context.Context, in *FileUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.FileUpdate(ctx, in, opts...)
}

func (m *defaultIam) FileDelete(ctx context.Context, in *FileDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.FileDelete(ctx, in, opts...)
}

func (m *defaultIam) FileList(ctx context.Context, in *FileListRequest, opts ...grpc.CallOption) (*FileListResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.FileList(ctx, in, opts...)
}

// Notice / Notification
func (m *defaultIam) NoticeCreate(ctx context.Context, in *NoticeCreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.NoticeCreate(ctx, in, opts...)
}

func (m *defaultIam) NoticeUpdate(ctx context.Context, in *NoticeUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.NoticeUpdate(ctx, in, opts...)
}

func (m *defaultIam) NoticeDelete(ctx context.Context, in *NoticeDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.NoticeDelete(ctx, in, opts...)
}

func (m *defaultIam) NoticeList(ctx context.Context, in *NoticeListRequest, opts ...grpc.CallOption) (*NoticeListResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.NoticeList(ctx, in, opts...)
}

func (m *defaultIam) NotificationList(ctx context.Context, in *NotificationListRequest, opts ...grpc.CallOption) (*NotificationListResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.NotificationList(ctx, in, opts...)
}

func (m *defaultIam) NotificationRead(ctx context.Context, in *NotificationReadRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.NotificationRead(ctx, in, opts...)
}

func (m *defaultIam) NotificationReadAll(ctx context.Context, in *NotificationReadAllRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.NotificationReadAll(ctx, in, opts...)
}

func (m *defaultIam) NotificationClearRead(ctx context.Context, in *NotificationClearReadRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.NotificationClearRead(ctx, in, opts...)
}

func (m *defaultIam) NotificationDelete(ctx context.Context, in *NotificationDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.NotificationDelete(ctx, in, opts...)
}

// OperationLog / LoginLog / PerformanceLog / AuditLog（列表/详情/统计；导出见
func (m *defaultIam) OperationLogList(ctx context.Context, in *OperationLogListRequest, opts ...grpc.CallOption) (*OperationLogListResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.OperationLogList(ctx, in, opts...)
}

func (m *defaultIam) OperationLogDetail(ctx context.Context, in *OperationLogDetailRequest, opts ...grpc.CallOption) (*OperationLogItem, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.OperationLogDetail(ctx, in, opts...)
}

func (m *defaultIam) LoginLogList(ctx context.Context, in *LoginLogListRequest, opts ...grpc.CallOption) (*LoginLogListResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.LoginLogList(ctx, in, opts...)
}

func (m *defaultIam) LoginLogDetail(ctx context.Context, in *LoginLogDetailRequest, opts ...grpc.CallOption) (*LoginLogItem, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.LoginLogDetail(ctx, in, opts...)
}

func (m *defaultIam) LoginLogStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LoginLogStatsResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.LoginLogStats(ctx, in, opts...)
}

func (m *defaultIam) PerformanceLogList(ctx context.Context, in *PerformanceLogListRequest, opts ...grpc.CallOption) (*PerformanceLogListResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.PerformanceLogList(ctx, in, opts...)
}

func (m *defaultIam) AuditLogList(ctx context.Context, in *AuditLogListRequest, opts ...grpc.CallOption) (*AuditLogListResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.AuditLogList(ctx, in, opts...)
}

func (m *defaultIam) AuditLogDetail(ctx context.Context, in *AuditLogDetailRequest, opts ...grpc.CallOption) (*AuditLogItem, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.AuditLogDetail(ctx, in, opts...)
}

// Metric / Monitor
func (m *defaultIam) MetricReport(ctx context.Context, in *MetricReportRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.MetricReport(ctx, in, opts...)
}

func (m *defaultIam) MetricStats(ctx context.Context, in *MetricStatsRequest, opts ...grpc.CallOption) (*MetricStatsResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.MetricStats(ctx, in, opts...)
}

func (m *defaultIam) MonitorStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MonitorStatsResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.MonitorStats(ctx, in, opts...)
}

func (m *defaultIam) MonitorStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MonitorStatusResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.MonitorStatus(ctx, in, opts...)
}

// Demo / DailyShortSentence
func (m *defaultIam) DemoCreate(ctx context.Context, in *DemoCreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DemoCreate(ctx, in, opts...)
}

func (m *defaultIam) DemoUpdate(ctx context.Context, in *DemoUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DemoUpdate(ctx, in, opts...)
}

func (m *defaultIam) DemoDelete(ctx context.Context, in *DemoDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DemoDelete(ctx, in, opts...)
}

func (m *defaultIam) DemoList(ctx context.Context, in *DemoListRequest, opts ...grpc.CallOption) (*DemoListResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DemoList(ctx, in, opts...)
}

func (m *defaultIam) DailyShortSentenceCreate(ctx context.Context, in *DailyShortSentenceCreateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DailyShortSentenceCreate(ctx, in, opts...)
}

func (m *defaultIam) DailyShortSentenceUpdate(ctx context.Context, in *DailyShortSentenceUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DailyShortSentenceUpdate(ctx, in, opts...)
}

func (m *defaultIam) DailyShortSentenceDelete(ctx context.Context, in *DailyShortSentenceDeleteRequest, opts ...grpc.CallOption) (*Empty, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DailyShortSentenceDelete(ctx, in, opts...)
}

func (m *defaultIam) DailyShortSentenceList(ctx context.Context, in *DailyShortSentenceListRequest, opts ...grpc.CallOption) (*DailyShortSentenceListResponse, error) {
	client := iam.NewIamClient(m.cli.Conn())
	return client.DailyShortSentenceList(ctx, in, opts...)
}
